{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from collections import Counter\n",
    "from enum import IntEnum\n",
    "from pathlib import Path\n",
    "import shutil\n",
    "import subprocess\n",
    "from tqdm import tqdm\n",
    "from typing import Dict, List, Optional"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Use examples in [python cookbook, 3rd Edition](https://www.amazon.com/Python-Cookbook-Third-David-Beazley/dp/1449340377) as test cases to verify the correctness of the implementation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "IWASM = Path(shutil.which(\"iwasm\"))\n",
    "\n",
    "PY2WASM = Path(shutil.which(\"py2wasm\"))\n",
    "\n",
    "PYTHON_COOKBOOK = Path.cwd().joinpath(\"./cookbook/src\")\n",
    "assert PYTHON_COOKBOOK.exists(), \"use `git submodule update` to fetch cookbook\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "class CaseErrorCode(IntEnum):\n",
    "    OK = 0\n",
    "    COMPILATION_FAILURE = 1\n",
    "    WASM_EXECUTION_FAILURE = 2\n",
    "    PY_EXECUTION_FAILURE = 3\n",
    "    DIFFERENT_RESULT = 4\n",
    "    BYPASS = 5\n",
    "\n",
    "    def __str__(self):\n",
    "        return f'{self.name}'\n",
    "\n",
    "class CaseResult:\n",
    "    def __init__(self, error_code: CaseErrorCode, msg: str):\n",
    "        self.error_code = error_code\n",
    "        self.msg = msg\n",
    "\n",
    "    def __repr__(self):\n",
    "        return f\"{self.error_code}\\n{self.msg}\"\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "For each case, we are going to:\n",
    "\n",
    "1. compile the python script to a WebAssembly core module \n",
    "2. run the python script \n",
    "3. run the WebAssembly core module\n",
    "4. compare both execution results of step 2 and step 3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def compile_py_2_wasm(py2wasm_bin: Path, py_file: Path, out_dir: Optional[Path]) -> Path:\n",
    "    if not out_dir is None:\n",
    "        out_dir.mkdir(parents=True, exist_ok=True)\n",
    "        wasm_file = out_dir.joinpath(py_file.stem + \".wasm\")\n",
    "    else:\n",
    "        wasm_file = py_file.with_suffix(\".wasm\")\n",
    "    \n",
    "    cmd = f\"{py2wasm_bin} {py_file} -o {wasm_file}\"\n",
    "    subprocess.run(cmd, cwd=Path.cwd(), capture_output=True, check=True, shell=True, universal_newlines=True, text=True)\n",
    "    return wasm_file\n",
    "\n",
    "def execute_py(py_file: Path) -> subprocess.CompletedProcess:\n",
    "    \"\"\"\n",
    "    Since relative pathes are used in examples.\n",
    "    \"\"\"\n",
    "    cwd = py_file.parent\n",
    "    cmd = f\"python {py_file}\"\n",
    "    return subprocess.run(cmd, cwd=cwd, capture_output=True, check=True, shell=True, universal_newlines=True, text=True)\n",
    "\n",
    "def execute_wasm(iwasm_bin: Path, wasm_file: Path) -> subprocess.CompletedProcess:\n",
    "    \"\"\"\n",
    "    To avoid the WASI pre-opens problem, run under the same directory with the wasm file\n",
    "    \"\"\"\n",
    "    cwd = wasm_file.parent\n",
    "    cmd = f\"{iwasm_bin} --dir=. {wasm_file.relative_to(cwd)}\"\n",
    "    return subprocess.run(cmd, cwd=cwd, capture_output=True, check=True, shell=True, universal_newlines=True, text=True)\n",
    "    \n",
    "\n",
    "def compare_result(expected: str, actual: str) -> bool:\n",
    "    return expected == actual\n",
    "\n",
    "##################################################\n",
    "def execute_case(py_file: Path, out_dir: Optional[Path]) -> CaseResult:\n",
    "    try:\n",
    "        wasm_file = compile_py_2_wasm(PY2WASM, py_file, out_dir)\n",
    "    except subprocess.CalledProcessError:\n",
    "        return CaseResult(CaseErrorCode.COMPILATION_FAILURE, \"\")\n",
    "\n",
    "    try:\n",
    "        p = execute_wasm(IWASM, wasm_file)\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        return CaseResult(CaseErrorCode.WASM_EXECUTION_FAILURE, e.stderr if e.stderr else e.stdout)\n",
    "    output_from_wasm = p.stdout\n",
    "\n",
    "    try:\n",
    "        p = execute_py(py_file)\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        return CaseResult(CaseErrorCode.PY_EXECUTION_FAILURE, e.stderr if e.stderr else e.stdout)\n",
    "    output_from_py = p.stdout\n",
    "\n",
    "    if not compare_result(output_from_py, output_from_wasm):\n",
    "        return CaseResult(CaseErrorCode.DIFFERENT_RESULT, f\"{'>' * 40}\\n{output_from_py}{'-' * 20} V.S. {'-' * 20}\\n{output_from_wasm}{'<' * 40}\")\n",
    "    \n",
    "    return CaseResult(CaseErrorCode.OK, \"\")\n",
    "\n",
    "def visit_case(py_file: Path, out_dir: Optional[Path]) -> CaseResult:\n",
    "    print(f\"py_file={py_file}, out_dir={out_dir}\")\n",
    "    return CaseResult(CaseErrorCode.OK, \"\")\n",
    "\n",
    "def execute_test(chapter: Path, bypass: List[str]) -> Dict[str, CaseResult]:\n",
    "    # list all sub-directories in chapter\n",
    "    chapter_tests = [x for x in chapter.iterdir() if x.is_dir()]\n",
    "\n",
    "    # walk\n",
    "    ret = {}\n",
    "    for test_dir in tqdm(chapter_tests):\n",
    "        if test_dir.name in bypass:\n",
    "            ret[case_name] = CaseResult(CaseErrorCode.BYPASS, \"\")\n",
    "            continue\n",
    "\n",
    "        # assume all .py under the test_dir are test cases\n",
    "        py_files = [x for x in test_dir.iterdir() if x.suffix == \".py\"]\n",
    "\n",
    "        for py_file in py_files:\n",
    "            result = execute_case(py_file, None)\n",
    "            # result = visit_case(py_file, None)\n",
    "            case_name = f\"{test_dir.name}.{py_file.stem}\"\n",
    "            ret[case_name] = result\n",
    "    \n",
    "    return ret\n",
    "\n",
    "def summarize_result(results: Dict[str, CaseResult]) -> None:\n",
    "    counter = Counter([x.error_code for x in results.values()])\n",
    "    print()\n",
    "    print(counter)\n",
    "    print()\n",
    "\n",
    "    # print failures\n",
    "    for k,v in results.items():\n",
    "        if v.error_code != CaseErrorCode.OK:\n",
    "            print(f\"{k} FAILED:\\n{v}\")\n",
    "            print()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 1. Data Structures And Algorithms\n",
    "\n",
    "`DIFFERENT_RESULT` in *finding_out_what_two_dictionaries_have_in_common* isn't a bug ðŸ˜„. It is caused by the different order of the keys in the dictionary.\n",
    "\n",
    "`EXECUTION_FAILURE` in *transforming_and_reducing_data_at_the_same_time* needs more investigation ðŸ”Ž. My first guess is about preopen."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 16/16 [04:38<00:00, 17.43s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 16, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 1})\n",
      "\n",
      "transforming_and_reducing_data_at_the_same_time.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 6, in <module>\n",
      "    files = os.listdir(os.path.expanduser('~'))\n",
      "    \n",
      "FileNotFoundError: [Errno 44] No such file or directory: '~'\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_1 = PYTHON_COOKBOOK.joinpath(\"1\")\n",
    "chapter_1_result = execute_test(chapter_1, [])\n",
    "summarize_result(chapter_1_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Investigation of *transforming_and_reducing_data_at_the_same_time*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 6, in <module>\n",
      "    files = os.listdir(os.path.expanduser('~'))\n",
      "    \n",
      "FileNotFoundError: [Errno 44] No such file or directory: '~'\n"
     ]
    }
   ],
   "source": [
    "! iwasm --dir=. --dir=/home/vscode ./cookbook/src/1/transforming_and_reducing_data_at_the_same_time/example.wasm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "error while pre-opening directory ~: 2\n",
      "\n"
     ]
    }
   ],
   "source": [
    "! iwasm --dir=. --dir=~ ./cookbook/src/1/transforming_and_reducing_data_at_the_same_time/example.wasm"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 2. Strings And Text\n",
    "\n",
    "There are `try...except...` in some cases. Need to deep dive into the wasm implementation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 13/13 [04:36<00:00, 21.25s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 13, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 2})\n",
      "\n",
      "writing_a_simple_recursive_descent_parser.plyexample FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "matching_strings_using_shell_wildcard_patterns.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Fatal Python error: init_sys_streams: can't initialize sys standard streams\n",
      "Python runtime state: core initialized\n",
      "ImportError: Frozen object named 'io' is invalid\n",
      "\n",
      "Current thread 0x00000000 (most recent call first):\n",
      "  <no Python frame>\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_2 = PYTHON_COOKBOOK.joinpath(\"2\")\n",
    "chapter_2_result = execute_test(chapter_2, [])\n",
    "summarize_result(chapter_2_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 3. Numbers, Dates, And Times"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 [00:36<00:00, 18.05s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 2})\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_3 = PYTHON_COOKBOOK.joinpath(\"3\")\n",
    "chapter_3_result = execute_test(chapter_3, [])\n",
    "summarize_result(chapter_3_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 4. Iterators And Generators"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 10/10 [02:52<00:00, 17.23s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 9, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 2})\n",
      "\n",
      "creating_data_processing_pipelines.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 3, in <module>\n",
      "    import gzip\n",
      "    \n",
      "  File \"./gzip.py\", line 9, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "how_to_flatten_a_nested_sequence.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 3, in <module>\n",
      "    from collections import Iterable\n",
      "    \n",
      "ImportError: cannot import name 'Iterable' from 'collections' (./collections/__init__.py)\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_4 = PYTHON_COOKBOOK.joinpath(\"4\")\n",
    "chapter_4_result = execute_test(chapter_4, [])\n",
    "summarize_result(chapter_4_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 5. Files And I/O"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 6/6 [01:41<00:00, 16.97s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 4, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 2})\n",
      "\n",
      "wrapping_an_existing_file_descriptor_as_a_file_object.echo FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echo.py\", line 26, in <module>\n",
      "    echo_server(('', 25000))\n",
      "\n",
      "  File \"./echo.py\", line 17, in echo_server\n",
      "    sock = socket(AF_INET, SOCK_STREAM)\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "adding_or_changing_the_encoding_of_an_already_open_file.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: out of bounds memory access\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_5 = PYTHON_COOKBOOK.joinpath(\"5\")\n",
    "chapter_5_result = execute_test(chapter_5, [])\n",
    "summarize_result(chapter_5_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 6. Data Encoding And Processing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 8/8 [03:50<00:00, 28.80s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 7, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 5, <CaseErrorCode.DIFFERENT_RESULT: 4>: 2})\n",
      "\n",
      "reading_and_writing_json_data.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "OrderedDict([('name', 'ACME'), ('shares', 50), ('price', 490.1)])\n",
      "ACME\n",
      "50\n",
      "490.1\n",
      "{\"__classname__\": \"Point\", \"x\": 3, \"y\": 4}\n",
      "<__main__.Point object at 0x7fbdfdce4790>\n",
      "3\n",
      "4\n",
      "-------------------- V.S. --------------------\n",
      "OrderedDict([('name', 'ACME'), ('shares', 50), ('price', 490.1)])\n",
      "ACME\n",
      "50\n",
      "490.1\n",
      "{\"__classname__\": \"Point\", \"x\": 3, \"y\": 4}\n",
      "<__main__.Point object at 0xbffd60>\n",
      "3\n",
      "4\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "parsing_xml_documents_with_namespaces.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "<Element '{http://www.w3.org/1999/xhtml}html' at 0x7f34b8318360>\n",
      "Hello World\n",
      "-------------------- V.S. --------------------\n",
      "<Element '{http://www.w3.org/1999/xhtml}html' at 0xc77338>\n",
      "Hello World\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "reading_nested_and_variable_sized_binary_structures.example4 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "reading_nested_and_variable_sized_binary_structures.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "reading_nested_and_variable_sized_binary_structures.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "parsing_simple_xml_data.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "object address  : 0xcf65f8\n",
      "object refcount : 1\n",
      "object type     : 0x8e2d9c\n",
      "object type name: TypeError\n",
      "object repr     : TypeError(\"'' object is not callable\")\n",
      "lost sys.stderr\n",
      "\n",
      "\n",
      "parsing_modifying_and_rewriting_xml.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 14, in <module>\n",
      "    nm_index = root.getchildren().index(root.find('nm'))\n",
      "    \n",
      "AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_6 = PYTHON_COOKBOOK.joinpath(\"6\")\n",
    "chapter_6_result = execute_test(chapter_6, [])\n",
    "summarize_result(chapter_6_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 7. Functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 7/7 [03:23<00:00, 29.05s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 6, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 5})\n",
      "\n",
      "inlining_callback_functions.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "making_an_n-argument_callable_work_as_a_callable_with_fewer_arguments.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example2.py\", line 21, in <module>\n",
      "    p = Pool()\n",
      "\n",
      "  File \"./multiprocessing/context.py\", line 118, in Pool\n",
      "  File \"./multiprocessing/pool.py\", line 30, in <module>\n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "making_an_n-argument_callable_work_as_a_callable_with_fewer_arguments.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example3.py\", line 16, in <module>\n",
      "    serv = TCPServer(('', 15000), partial(EchoHandler, ack=b'RECEIVED:'))\n",
      "\n",
      "  File \"./socketserver.py\", line 452, in __init__\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "accessing_variables_defined_inside_a_closure.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example2.py\", line 34, in <module>\n",
      "    s.push(10)\n",
      "\n",
      "AttributeError: 'ClosureInstance' object has no attribute 'push'\n",
      "\n",
      "\n",
      "accessing_variables_defined_inside_a_closure.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example3.py\", line 27, in <module>\n",
      "    print(timeit('s.push(1); s.pop()', 'from __main__ import s'))\n",
      "\n",
      "  File \"./timeit.py\", line 237, in timeit\n",
      "  File \"./timeit.py\", line 180, in timeit\n",
      "  File \"<timeit-src>\", line 6, in inner\n",
      "AttributeError: 'ClosureInstance' object has no attribute 'push'\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_7 = PYTHON_COOKBOOK.joinpath(\"7\")\n",
    "chapter_7_result = execute_test(chapter_7, [])\n",
    "summarize_result(chapter_7_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 8. Classes And Objects"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 24/24 [13:43<00:00, 34.29s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 32, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 16, <CaseErrorCode.DIFFERENT_RESULT: 4>: 1})\n",
      "\n",
      "managing_memory_in_cyclic_data_structures.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "making_objects_support_the_context_manager_protocol.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example2.py\", line 24, in <module>\n",
      "    with conn as s:\n",
      "\n",
      "  File \"./example2.py\", line 11, in __enter__\n",
      "    sock = socket(self.family, self.type)\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "making_objects_support_the_context_manager_protocol.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example1.py\", line 26, in <module>\n",
      "    with c as s:\n",
      "\n",
      "  File \"./example1.py\", line 13, in __enter__\n",
      "    self.sock = socket(self.family, self.type)\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "implementing_the_visitor_pattern_without_recursion.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: wasm operand stack overflow\n",
      "\n",
      "\n",
      "how_to_define_an_interface_or_abstract_base_class.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "creating_an_instance_without_invoking_init.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "creating_managed_attributes.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "implementing_stateful_objects_or_state_machines.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "implementing_stateful_objects_or_state_machines.example1 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "<__main__.ClosedConnection object at 0x7f6233c98b50>\n",
      "Not open\n",
      "<__main__.OpenConnection object at 0x7f6233c98b50>\n",
      "reading\n",
      "<__main__.ClosedConnection object at 0x7f6233c98b50>\n",
      "-------------------- V.S. --------------------\n",
      "<__main__.ClosedConnection object at 0xaa6660>\n",
      "Not open\n",
      "<__main__.OpenConnection object at 0xaa6660>\n",
      "reading\n",
      "<__main__.ClosedConnection object at 0xaa6660>\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "lazily_computed_attributes.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "implementing_custom_containers.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example2.py\", line 3, in <module>\n",
      "    class Items(collections.MutableSequence):\n",
      "    \n",
      "AttributeError: module 'collections' has no attribute 'MutableSequence'\n",
      "\n",
      "\n",
      "implementing_custom_containers.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example1.py\", line 6, in <module>\n",
      "    class SortedItems(collections.Sequence):\n",
      "    \n",
      "AttributeError: module 'collections' has no attribute 'Sequence'\n",
      "\n",
      "\n",
      "extending_a_property_in_a_subclass.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "extending_a_property_in_a_subclass.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "how_to_define_more_than_one_constructor_in_a_class.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "how_to_define_more_than_one_constructor_in_a_class.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "making_classes_support_comparison_operations.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_8 = PYTHON_COOKBOOK.joinpath(\"8\")\n",
    "chapter_8_result = execute_test(chapter_8, [])\n",
    "summarize_result(chapter_8_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 9. Metaprogramming\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 23/23 [10:24<00:00, 27.14s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 26, <CaseErrorCode.OK: 0>: 7, <CaseErrorCode.DIFFERENT_RESULT: 4>: 3})\n",
      "\n",
      "using_metaclasses_to_control_instance_creation.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "preserving_function_metadata_when_writing_decorators.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_a_decorator_that_takes_an_optional_argument.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_decorators_as_classes.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_decorators_as_classes.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_decorators_as_classes.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_a_decorator_that_takes_arguments.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "disassembling_python_byte_code.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_classes_programmatically.example1 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "<types.Stock object at 0x7f4af90049d0>\n",
      "4555.0\n",
      "-------------------- V.S. --------------------\n",
      "<types.Stock object at 0xbf5610>\n",
      "4555.0\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "applying_decorators_to_class_and_static_methods.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "avoiding_repetitive_property_methods.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "enforcing_type_checking_on_a_function_using_a_decorator.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_a_decorator_with_user_adjustable_attributes.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_a_decorator_with_user_adjustable_attributes.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_decorators_as_part_of_a_class.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_decorators_as_part_of_a_class.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "capturing_class_attribute_definition_order.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "capturing_class_attribute_definition_order.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "parsing_and_analyzing_python_source.example1 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "Loaded: {'print', 'i', 'range'}\n",
      "Stored: {'i'}\n",
      "Deleted: {'i'}\n",
      "-------------------- V.S. --------------------\n",
      "Loaded: {'i', 'print', 'range'}\n",
      "Stored: {'i'}\n",
      "Deleted: {'i'}\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "parsing_and_analyzing_python_source.namelower FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "enforcing_coding_conventions_in_classes.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "enforcing_coding_conventions_in_classes.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example1.py\", line 18, in <module>\n",
      "    class B(Root):\n",
      "    \n",
      "  File \"./example1.py\", line 7, in __new__\n",
      "    raise TypeError('Bad attribute name: ' + name)\n",
      "\n",
      "TypeError: Bad attribute name: fooBar\n",
      "\n",
      "\n",
      "unwrapping_a_decorator.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_context_managers_the_easy_way.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_context_managers_the_easy_way.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "multiple_dispatch_with_function_annotations.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "multiple_dispatch_with_function_annotations.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_a_metaclass_that_takes_optional_arguments.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "executing_code_with_local_side_effects.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      ":::: Running test()\n",
      "14\n",
      ":::: Running test1()\n",
      "0\n",
      ":::: Running test2()\n",
      "before: {'x': 0}\n",
      "after: {'x': 1, 'loc': {...}}\n",
      "x = 0\n",
      ":::: Running test3()\n",
      "{'x': 0}\n",
      "{'x': 1, 'loc': {...}}\n",
      "{'x': 0, 'loc': {...}}\n",
      ":::: Running test4()\n",
      "14\n",
      "-------------------- V.S. --------------------\n",
      ":::: Running test()\n",
      "14\n",
      ":::: Running test1()\n",
      "0\n",
      ":::: Running test2()\n",
      "before: {'x': 0}\n",
      "after: {'x': 1, 'loc': {...}}\n",
      "x = 0\n",
      ":::: Running test3()\n",
      "{'x': 0}\n",
      "{'x': 1, 'loc': {...}}\n",
      "{'x': 1, 'loc': {...}}\n",
      ":::: Running test4()\n",
      "14\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_9 = PYTHON_COOKBOOK.joinpath(\"9\")\n",
    "chapter_9_result = execute_test(chapter_9, [])\n",
    "summarize_result(chapter_9_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 10. Modules And Packages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4/4 [02:46<00:00, 41.71s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 5, <CaseErrorCode.OK: 0>: 4})\n",
      "\n",
      "monkeypatching_modules_on_import.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "loading_modules_from_a_remote_machine_using_import_hooks.metaexample FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./metaexample.py\", line 10, in <module>\n",
      "    import urlimport\n",
      "    \n",
      "  File \"./urlimport.py\", line 6, in <module urlimport>\n",
      "    from urllib.request import urlopen\n",
      "    \n",
      "  File \"./urllib/request.py\", line 88, in <module>\n",
      "  File \"./http/client.py\", line 71, in <module>\n",
      "  File \"./email/parser.py\", line 12, in <module>\n",
      "  File \"./email/feedparser.py\", line 27, in <module>\n",
      "  File \"./email/_policybase.py\", line 7, in <module>\n",
      "  File \"./email/header.py\", line 17, in <module>\n",
      "ModuleNotFoundError: No module named 'email.base64mime'\n",
      "\n",
      "\n",
      "loading_modules_from_a_remote_machine_using_import_hooks.pathexample FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./pathexample.py\", line 8, in <module>\n",
      "    import urlimport\n",
      "    \n",
      "  File \"./urlimport.py\", line 6, in <module urlimport>\n",
      "    from urllib.request import urlopen\n",
      "    \n",
      "  File \"./urllib/request.py\", line 88, in <module>\n",
      "  File \"./http/client.py\", line 71, in <module>\n",
      "  File \"./email/parser.py\", line 12, in <module>\n",
      "  File \"./email/feedparser.py\", line 27, in <module>\n",
      "  File \"./email/_policybase.py\", line 7, in <module>\n",
      "  File \"./email/header.py\", line 17, in <module>\n",
      "ModuleNotFoundError: No module named 'email.base64mime'\n",
      "\n",
      "\n",
      "loading_modules_from_a_remote_machine_using_import_hooks.urlimport FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./urlimport.py:5: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses\n",
      "  import imp\n",
      "\n",
      "\n",
      "loading_modules_from_a_remote_machine_using_import_hooks.explicit_load FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./explicit_load.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses\n",
      "  import imp\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_10 = PYTHON_COOKBOOK.joinpath(\"10\")\n",
    "chapter_10_result = execute_test(chapter_10, [])\n",
    "summarize_result(chapter_10_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 11. Network And Web Programming"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 12/12 [23:44<00:00, 118.69s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 46, <CaseErrorCode.OK: 0>: 4})\n",
      "\n",
      "event_driven_io_explained.tcpclient FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./tcpclient.py\", line 3, in <module>\n",
      "    s = socket(AF_INET, SOCK_STREAM)\n",
      "    \n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "event_driven_io_explained.threadpool FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./threadpool.py\", line 63, in <module>\n",
      "    pool = ThreadPoolHandler(16)\n",
      "\n",
      "  File \"./threadpool.py\", line 7, in __init__\n",
      "    self.signal_done_sock, self.done_sock = socket.socketpair()\n",
      "\n",
      "  File \"./socket.py\", line 631, in socketpair\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "event_driven_io_explained.udpclient FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./udpclient.py\", line 2, in <module>\n",
      "    s = socket(AF_INET, SOCK_DGRAM)\n",
      "    \n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "event_driven_io_explained.thrpoolclient FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./thrpoolclient.py\", line 2, in <module>\n",
      "    sock = socket(AF_INET, SOCK_DGRAM)\n",
      "    \n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "event_driven_io_explained.tcpserver FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./tcpserver.py\", line 60, in <module>\n",
      "    handlers.append(TCPServer(('',16000), TCPEchoClient, handlers))\n",
      " \n",
      "  File \"./tcpserver.py\", line 8, in __init__\n",
      "    self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "event_driven_io_explained.udpserver FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./udpserver.py\", line 28, in <module>\n",
      "    handlers = [ UDPTimeServer(('',14000)), UDPEchoServer(('',15000))  ]\n",
      "\n",
      "  File \"./udpserver.py\", line 8, in __init__\n",
      "    self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "interacting_with_http_services_as_a_client.example4 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example4.py\", line 3, in <module>\n",
      "    import requests\n",
      "    \n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./requests/__init__.py\", line 43, in <module requests>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./urllib3/__init__.py\", line 14, in <module urllib3>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./urllib3/exceptions.py\", line 7, in <module urllib3.exceptions>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./http/client.py\", line 71, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/parser.py\", line 12, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/feedparser.py\", line 27, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/_policybase.py\", line 9, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/utils.py\", line 28, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "TypeError: bad argument type for built-in operation\n",
      "\n",
      "\n",
      "interacting_with_http_services_as_a_client.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example2.py\", line 3, in <module>\n",
      "    from urllib import request, parse\n",
      "    \n",
      "  File \"./urllib/request.py\", line 88, in <module>\n",
      "  File \"./http/client.py\", line 71, in <module>\n",
      "  File \"./email/parser.py\", line 12, in <module>\n",
      "  File \"./email/feedparser.py\", line 27, in <module>\n",
      "  File \"./email/_policybase.py\", line 9, in <module>\n",
      "ModuleNotFoundError: No module named 'email.utils'\n",
      "\n",
      "\n",
      "interacting_with_http_services_as_a_client.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example1.py\", line 3, in <module>\n",
      "    from urllib import request, parse\n",
      "    \n",
      "  File \"./urllib/request.py\", line 88, in <module>\n",
      "  File \"./http/client.py\", line 71, in <module>\n",
      "  File \"./email/parser.py\", line 12, in <module>\n",
      "  File \"./email/feedparser.py\", line 27, in <module>\n",
      "  File \"./email/_policybase.py\", line 9, in <module>\n",
      "ModuleNotFoundError: No module named 'email.utils'\n",
      "\n",
      "\n",
      "interacting_with_http_services_as_a_client.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: out of bounds memory access\n",
      "\n",
      "\n",
      "creating_a_udp_server.timeserv1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./timeserv1.py\", line 13, in <module>\n",
      "    serv = UDPServer(('', 20000), TimeHandler)\n",
      "\n",
      "  File \"./socketserver.py\", line 452, in __init__\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_udp_server.client FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./client.py\", line 3, in <module>\n",
      "    s = socket(AF_INET, SOCK_DGRAM)\n",
      "    \n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_udp_server.timeserv2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./timeserv2.py\", line 14, in <module>\n",
      "    time_server(('', 20000))\n",
      "\n",
      "  File \"./timeserv2.py\", line 5, in time_server\n",
      "    sock = socket(AF_INET, SOCK_DGRAM)\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "simple_authentication_of_clients.server FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./server.py\", line 26, in <module>\n",
      "    echo_server(('', 18000))\n",
      "    \n",
      "  File \"./server.py\", line 17, in echo_server\n",
      "    s = socket(AF_INET, SOCK_STREAM)\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "simple_authentication_of_clients.client FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./client.py\", line 6, in <module>\n",
      "    s = socket(AF_INET, SOCK_STREAM)\n",
      "    \n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "simple_remote_procedure_call_with_xmlrpc.keyserv FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./keyserv.py\", line 1, in <module>\n",
      "    from xmlrpc.server import SimpleXMLRPCServer\n",
      "    \n",
      "  File \"./xmlrpc/server.py\", line 107, in <module>\n",
      "  File \"./xmlrpc/client.py\", line 136, in <module>\n",
      "  File \"./http/client.py\", line 71, in <module>\n",
      "  File \"./email/parser.py\", line 12, in <module>\n",
      "  File \"./email/feedparser.py\", line 27, in <module>\n",
      "  File \"./email/_policybase.py\", line 7, in <module>\n",
      "  File \"./email/header.py\", line 17, in <module>\n",
      "ModuleNotFoundError: No module named 'email.base64mime'\n",
      "\n",
      "\n",
      "simple_remote_procedure_call_with_xmlrpc.client FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "object address  : 0xccafc8\n",
      "object refcount : 1\n",
      "object type     : 0x89dfcc\n",
      "object type name: TypeError\n",
      "object repr     : TypeError(\"'' object is not callable\")\n",
      "lost sys.stderr\n",
      "\n",
      "\n",
      "implementing_remote_procedure_call.rpcserver FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./rpcserver.py\", line 26, in <module>\n",
      "    from multiprocessing.connection import Listener\n",
      "    \n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "implementing_remote_procedure_call.rpcclient FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./rpcclient.py\", line 16, in <module>\n",
      "    from multiprocessing.connection import Client\n",
      "    \n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "implementing_remote_procedure_call.jsonrpcserver FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./jsonrpcserver.py\", line 26, in <module>\n",
      "    from multiprocessing.connection import Listener\n",
      "    \n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "implementing_remote_procedure_call.jsonrpclient FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./jsonrpclient.py\", line 14, in <module>\n",
      "    from multiprocessing.connection import Client\n",
      "    \n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "simple_communication_between_interpreters.echoclient FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoclient.py\", line 1, in <module>\n",
      "    from multiprocessing.connection import Client\n",
      "    \n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "simple_communication_between_interpreters.echoserv FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoserv.py\", line 1, in <module>\n",
      "    from multiprocessing.connection import Listener\n",
      "    \n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.servermp FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./servermp.py\", line 2, in <module>\n",
      "    from multiprocessing.connection import Listener\n",
      "    \n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.workermp FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./workermp.py\", line 3, in <module>\n",
      "    from multiprocessing.connection import Client\n",
      "    \n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.server FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Usage: server.py server_address port\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.client1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./client1.py\", line 3, in <module>\n",
      "    s = socket(AF_INET, SOCK_STREAM)\n",
      "    \n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.server1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./server1.py\", line 33, in <module>\n",
      "    c1, c2 = multiprocessing.Pipe()\n",
      "\n",
      "  File \"./multiprocessing/context.py\", line 62, in Pipe\n",
      "  File \"./multiprocessing/connection.py\", line 22, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.worker FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Usage: worker.py server_address\n",
      "\n",
      "\n",
      "creating_a_simple_rest_based_interface.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example1.py\", line 36, in <module>\n",
      "    from resty import PathDispatcher\n",
      "\n",
      "  File \"./resty.py\", line 3, in <module resty>\n",
      "    import cgi\n",
      "    \n",
      "  File \"./cgi.py\", line 45, in <module>\n",
      "ModuleNotFoundError: No module named 'email.message'\n",
      "\n",
      "\n",
      "creating_a_simple_rest_based_interface.client1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./client1.py\", line 1, in <module>\n",
      "    from urllib.request import urlopen\n",
      "    \n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./urllib/request.py\", line 88, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./http/client.py\", line 72, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1138, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 1078, in _find_spec\n",
      "TypeError: 'tuple' object is not callable\n",
      "\n",
      "\n",
      "adding_ssl_to_network_servers.echoclient FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoclient.py\", line 7, in <module>\n",
      "    import ssl\n",
      "    \n",
      "  File \"./ssl.py\", line 100, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "adding_ssl_to_network_servers.ssl_xmlrpc_server FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./ssl_xmlrpc_server.py\", line 5, in <module>\n",
      "    import ssl\n",
      "    \n",
      "  File \"./ssl.py\", line 100, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "adding_ssl_to_network_servers.sslmixin FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./sslmixin.py\", line 1, in <module>\n",
      "    import ssl\n",
      "    \n",
      "  File \"./ssl.py\", line 100, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "adding_ssl_to_network_servers.echoserv FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoserv.py\", line 2, in <module>\n",
      "    from socket import SOL_SOCKET, SO_REUSEADDR\n",
      "    \n",
      "ImportError: cannot import name 'SO_REUSEADDR' from 'socket' (./socket.py)\n",
      "\n",
      "\n",
      "adding_ssl_to_network_servers.ssl_xmlrpc_client FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: out of bounds memory access\n",
      "\n",
      "\n",
      "zero_copy_sending_and_receiving_of_large_arrays.server FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./server.py\", line 4, in <module>\n",
      "    s = socket(AF_INET, SOCK_STREAM)\n",
      "    \n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "zero_copy_sending_and_receiving_of_large_arrays.client FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./client.py\", line 4, in <module>\n",
      "    c = socket(AF_INET, SOCK_STREAM)\n",
      "    \n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoclient FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoclient.py\", line 2, in <module>\n",
      "    s = socket(AF_INET, SOCK_STREAM)\n",
      "    \n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_tcp_server.threadedserv FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./threadedserv.py\", line 14, in <module>\n",
      "    serv = TCPServer(('', 20000), EchoHandler)\n",
      "\n",
      "  File \"./socketserver.py\", line 452, in __init__\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoserv2.py\", line 12, in <module>\n",
      "    serv = TCPServer(('', 20000), EchoHandler)\n",
      "\n",
      "  File \"./socketserver.py\", line 452, in __init__\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv5 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoserv5.py\", line 23, in <module>\n",
      "    echo_server(('', 20000))\n",
      "\n",
      "  File \"./echoserv5.py\", line 15, in echo_server\n",
      "    sock = socket(AF_INET, SOCK_STREAM)\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoserv.py\", line 13, in <module>\n",
      "    serv = TCPServer(('', 20000), EchoHandler)\n",
      "\n",
      "  File \"./socketserver.py\", line 452, in __init__\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv4 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoserv4.py\", line 20, in <module>\n",
      "    serv = TCPServer(('', 20000), EchoHandler)\n",
      "\n",
      "  File \"./socketserver.py\", line 452, in __init__\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoserv3.py\", line 14, in <module>\n",
      "    serv = TCPServer(('', 20000), EchoHandler, bind_and_activate=False)\n",
      "\n",
      "  File \"./socketserver.py\", line 452, in __init__\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./echoserv1.py\", line 13, in <module>\n",
      "    serv = TCPServer(('', 20000), EchoHandler)\n",
      "\n",
      "  File \"./socketserver.py\", line 452, in __init__\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_11 = PYTHON_COOKBOOK.joinpath(\"11\")\n",
    "chapter_11_result = execute_test(chapter_11, [])\n",
    "summarize_result(chapter_11_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 12. Concurrency"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 13/13 [08:39<00:00, 39.97s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 25, <CaseErrorCode.OK: 0>: 3})\n",
      "\n",
      "how_to_start_and_stop_threads.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_an_actor_task.actor FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_an_actor_task.tagged FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "defining_an_actor_task.worker FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "using_generators_as_an_alternative_to_threads.netsched FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./netsched.py\", line 159, in <module>\n",
      "    sched.run()\n",
      "\n",
      "  File \"./netsched.py\", line 62, in run\n",
      "    r = task.send(msg)\n",
      "\n",
      "  File \"./netsched.py\", line 137, in server_loop\n",
      "    s = Socket(socket(AF_INET,SOCK_STREAM))\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "storing_thread_specific_state.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "storing_thread_specific_state.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "launching_a_daemon_process_on_unix.daemon FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Usage: daemon.wasm [start|stop]\n",
      "\n",
      "\n",
      "implementing_publish_subscribe_messaging.exchange2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "how_to_determine_if_a_thread_has_started.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "how_to_determine_if_a_thread_has_started.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "how_to_determine_if_a_thread_has_started.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "locking_with_deadlock_avoidance.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "locking_with_deadlock_avoidance.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "locking_with_deadlock_avoidance.deadlock FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "locking_with_deadlock_avoidance.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "how_to_lock_critical_sections.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "polling_multiple_thread_queues.pqueue FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./pqueue.py\", line 49, in <module>\n",
      "    q1 = PollableQueue()\n",
      "\n",
      "  File \"./pqueue.py\", line 10, in __init__\n",
      "    self._putsocket, self._getsocket = socket.socketpair()\n",
      "\n",
      "  File \"./socket.py\", line 631, in socketpair\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "how_to_communicate_between_threads.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "how_to_communicate_between_threads.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "simple_parallel_programming.findrobots FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./findrobots.py\", line 3, in <module>\n",
      "    import gzip\n",
      "    \n",
      "  File \"./gzip.py\", line 9, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "simple_parallel_programming.findrobots_par FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./findrobots_par.py\", line 3, in <module>\n",
      "    import gzip\n",
      "    \n",
      "  File \"./gzip.py\", line 9, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "how_to_create_a_thread_pool.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "how_to_create_a_thread_pool.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example1.py\", line 27, in <module>\n",
      "    echo_server(('',15000))\n",
      "    \n",
      "  File \"./example1.py\", line 20, in echo_server\n",
      "    sock = socket(AF_INET, SOCK_STREAM)\n",
      "\n",
      "  File \"./socket.py\", line 232, in __init__\n",
      "OSError: [Errno 58] Not supported\n",
      "\n",
      "\n",
      "how_to_create_a_thread_pool.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "TypeError: unsupported operand type(s) for +=: '' and 'str'\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"./example3.py\", line 2, in <module>\n",
      "    import urllib.request\n",
      "    \n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./urllib/request.py\", line 88, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./http/client.py\", line 71, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/parser.py\", line 12, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/feedparser.py\", line 27, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/_policybase.py\", line 7, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/header.py\", line 20, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/charset.py\", line 18, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./email/encoders.py\", line 16, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1138, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 1078, in _find_spec\n",
      "SystemError: <class '_frozen_importlib.ModuleSpec'> returned a result with an exception set\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_12 = PYTHON_COOKBOOK.joinpath(\"12\")\n",
    "chapter_12_result = execute_test(chapter_12, [])\n",
    "summarize_result(chapter_12_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chatper 13. Utility Scripting And System Administration"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 11/11 [03:52<00:00, 21.10s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 9, <CaseErrorCode.OK: 0>: 4})\n",
      "\n",
      "parsing_command_line_options.search FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "usage: search.wasm [-h] -p pattern [-v] [-o OUTFILE] [--speed {fast,slow}]\n",
      "                   [filename ...]\n",
      "search.wasm: error: the following arguments are required: -p/--pat\n",
      "\n",
      "\n",
      "prompting_for_a_password_at_runtime.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 3, in <module>\n",
      "    user = getpass.getuser()\n",
      "    \n",
      "  File \"./getpass.py\", line 168, in getuser\n",
      "ModuleNotFoundError: No module named 'pwd'\n",
      "\n",
      "\n",
      "generating_a_range_of_ip_addresses_from_a_cidr_address.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 25, in <module>\n",
      "    for a in cidr_range('12:3456:78:90ab:cd:ef01:23:34/125'):\n",
      " \n",
      "  File \"./example.py\", line 9, in cidr_range\n",
      "    addr_bytes = inet_pton(family, address)\n",
      "\n",
      "OSError: can't use AF_INET6, IPv6 is disabled\n",
      "\n",
      "\n",
      "putting_limits_on_memory_and_cpu_usage.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 2, in <module>\n",
      "    import resource\n",
      "    \n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "finding_files.modified_within FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Usage: modified_within.wasm dir seconds\n",
      "\n",
      "\n",
      "making_a_stopwatch.stopwatch FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "executing_an_external_command_and_getting_its_output.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example2.py\", line 11, in <module>\n",
      "    p = subprocess.Popen(['wc'],\n",
      "    \n",
      "  File \"./subprocess.py\", line 818, in __init__\n",
      "OSError: [Errno 58] wasi does not support processes.\n",
      "\n",
      "\n",
      "executing_an_external_command_and_getting_its_output.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example1.py\", line 3, in <module>\n",
      "    out_bytes = subprocess.check_output(['netstat', '-a'])\n",
      "\n",
      "  File \"./subprocess.py\", line 466, in check_output\n",
      "  File \"./subprocess.py\", line 548, in run\n",
      "  File \"./subprocess.py\", line 818, in __init__\n",
      "OSError: [Errno 58] wasi does not support processes.\n",
      "\n",
      "\n",
      "getting_the_terminal_size.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 2, in <module>\n",
      "    sz = os.get_terminal_size()\n",
      "    \n",
      "AttributeError: module 'os' has no attribute 'get_terminal_size'\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_13 = PYTHON_COOKBOOK.joinpath(\"13\")\n",
    "chapter_13_result = execute_test(chapter_13, [])\n",
    "summarize_result(chapter_13_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 14. Testing, Debugging, And Exceptions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 7/7 [11:02<00:00, 94.63s/it] "
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 5, <CaseErrorCode.OK: 0>: 3})\n",
      "\n",
      "logging_test_output_to_a_file.test FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "make_your_programs_run_faster.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "skipping_or_anticipating_test_failures.test FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "testing_for_exceptional_conditions_in_unit_tests.test FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "profiling_and_timing_your_program.timethis FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_14 = PYTHON_COOKBOOK.joinpath(\"14\")\n",
    "chapter_14_result = execute_test(chapter_14, [])\n",
    "summarize_result(chapter_14_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 15. C Extensions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 16/16 [15:27<00:00, 57.98s/it] "
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 31})\n",
      "\n",
      "working_with_c_strings_of_dubious_encoding.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "working_with_c_strings_of_dubious_encoding.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "passing_null_terminated_strings_to_c_libraries.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "passing_null_terminated_strings_to_c_libraries.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "wrapping_existing_c_code_with_cython.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup\n",
      "Traceback (most recent call last):\n",
      "  File \"./setup.py\", line 3, in <module>\n",
      "    from Cython.Distutils import build_ext\n",
      "    \n",
      "ModuleNotFoundError: No module named 'Cython'\n",
      "\n",
      "\n",
      "wrapping_existing_c_code_with_cython.setup_alt FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup_alt.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup\n",
      "Traceback (most recent call last):\n",
      "  File \"./setup_alt.py\", line 3, in <module>\n",
      "    from Cython.Distutils import build_ext\n",
      "    \n",
      "ModuleNotFoundError: No module named 'Cython'\n",
      "\n",
      "\n",
      "wrapping_existing_c_code_with_cython.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "passing_unicode_strings_to_c_libraries.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "passing_unicode_strings_to_c_libraries.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "diagnosing_segmentation_faults.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "diagnosing_segmentation_faults.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 2, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "wrapping_c_code_with_swig.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "wrapping_c_code_with_swig.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "writing_an_extension_function_that_operates_on_arrays.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "writing_an_extension_function_that_operates_on_arrays.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 2, in <module>\n",
      "    from sample import avg\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "consuming_an_iterable_from_c.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "consuming_an_iterable_from_c.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "using_cython_to_write_high_performance_array_operations.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup\n",
      "Traceback (most recent call last):\n",
      "  File \"./setup.py\", line 4, in <module>\n",
      "    from Cython.Distutils import build_ext\n",
      "    \n",
      "ModuleNotFoundError: No module named 'Cython'\n",
      "\n",
      "\n",
      "using_cython_to_write_high_performance_array_operations.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 2, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "defining_and_exporting_c_apis_from_extension_modules.ptsetup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./ptsetup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: ptsetup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: ptsetup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: ptsetup.wasm --help-commands\n",
      "   or: ptsetup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "defining_and_exporting_c_apis_from_extension_modules.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "defining_and_exporting_c_apis_from_extension_modules.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "accessing_c_code_using_ctypes.sample FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: unreachable\n",
      "\n",
      "\n",
      "accessing_c_code_using_ctypes.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: unreachable\n",
      "\n",
      "\n",
      "reading_file_like_objects_from_c.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "reading_file_like_objects_from_c.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 2, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "managing_opaque_pointers_in_c_extension_modules.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "managing_opaque_pointers_in_c_extension_modules.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "turning_a_function_pointer_into_a_callable.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Exception: unreachable\n",
      "\n",
      "\n",
      "writing_a_simple_c_extension_module.setup FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./setup.py:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives\n",
      "  from distutils.core import setup, Extension\n",
      "usage: setup.wasm [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.wasm --help [cmd1 cmd2 ...]\n",
      "   or: setup.wasm --help-commands\n",
      "   or: setup.wasm cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "writing_a_simple_c_extension_module.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    import sample\n",
      "    \n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_15 = PYTHON_COOKBOOK.joinpath(\"15\")\n",
    "chapter_15_result = execute_test(chapter_15, [])\n",
    "summarize_result(chapter_15_result)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Summary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 180, <CaseErrorCode.OK: 0>: 114, <CaseErrorCode.DIFFERENT_RESULT: 4>: 6})\n",
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_x_results = {\n",
    "    **chapter_1_result,\n",
    "    **chapter_2_result,\n",
    "    **chapter_3_result,\n",
    "    **chapter_4_result,\n",
    "    **chapter_5_result,\n",
    "    **chapter_6_result,\n",
    "    **chapter_7_result,\n",
    "    **chapter_8_result,\n",
    "    **chapter_9_result,\n",
    "    **chapter_10_result,\n",
    "    **chapter_11_result,\n",
    "    **chapter_12_result,\n",
    "    **chapter_13_result,\n",
    "    **chapter_14_result,\n",
    "    **chapter_15_result,\n",
    "}\n",
    "\n",
    "\n",
    "x_counters = Counter([x.error_code for x in chapter_x_results.values()])\n",
    "print()\n",
    "print(x_counters)\n",
    "print()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
