{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from collections import Counter\n",
    "from enum import IntEnum\n",
    "from pathlib import Path\n",
    "import pickle\n",
    "from pprint import pprint\n",
    "import shutil\n",
    "import subprocess\n",
    "from tqdm import tqdm\n",
    "from typing import Dict, List, Optional"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functionality Test about pywasm and wamr"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Use examples in [python cookbook, 3rd Edition](https://www.amazon.com/Python-Cookbook-Third-David-Beazley/dp/1449340377) as test cases to verify the correctness of the implementation.\n",
    "\n",
    "![](https://m.media-amazon.com/images/I/513ALClCHCL._SY445_SX342_.jpg)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "IWASM = Path(shutil.which(\"iwasm\"))\n",
    "\n",
    "PY2WASM = Path(shutil.which(\"py2wasm\"))\n",
    "\n",
    "PYTHON_COOKBOOK = Path.cwd().joinpath(\"./cookbook/src\")\n",
    "assert PYTHON_COOKBOOK.exists(), \"use `git submodule update` to fetch cookbook\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "class CaseErrorCode(IntEnum):\n",
    "    OK = 0\n",
    "    COMPILATION_FAILURE = 1\n",
    "    WASM_EXECUTION_FAILURE = 2\n",
    "    PY_EXECUTION_FAILURE = 3\n",
    "    DIFFERENT_RESULT = 4\n",
    "    BYPASS = 5\n",
    "    WASM_EXECUTION_TIMEOUT = 6\n",
    "    PY_EXECUTION_TIMEOUT = 7\n",
    "\n",
    "    def __str__(self):\n",
    "        return f'{self.name}'\n",
    "\n",
    "class CaseResult:\n",
    "    def __init__(self, error_code: CaseErrorCode, msg: str):\n",
    "        self.error_code = error_code\n",
    "        self.msg = msg\n",
    "\n",
    "    def __repr__(self):\n",
    "        return f\"{self.error_code}\\n{self.msg}\"\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "For each case, we are going to:\n",
    "\n",
    "1. compile the python script to a WebAssembly core module\n",
    "2. run the python script via python 3.11.9\n",
    "3. run the WebAssembly core module via iwasm_wasi_interp_d3e89895b\n",
    "4. compare both execution results of step 2 and step 3\n",
    "\n",
    "*iwasm* needs to fully support wasm32-wasi. Its recommended compilation options are: `-DWAMR_BUILD_REF_TYPES=1 -DWAMR_BUILD_LIBC_BUILTIN=0`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def compile_py_2_wasm(py2wasm_bin: Path, py_file: Path, out_dir: Optional[Path]) -> Path:\n",
    "    if not out_dir is None:\n",
    "        out_dir.mkdir(parents=True, exist_ok=True)\n",
    "        wasm_file = out_dir.joinpath(py_file.stem + \".wasm\")\n",
    "    else:\n",
    "        wasm_file = py_file.with_suffix(\".wasm\")\n",
    "    \n",
    "    cmd = f\"{py2wasm_bin} {py_file} -o {wasm_file}\"\n",
    "    subprocess.run(cmd, cwd=Path.cwd(), capture_output=True, check=True, shell=True, universal_newlines=True, text=True, timeout=120)\n",
    "    return wasm_file\n",
    "\n",
    "def execute_py(py_file: Path) -> subprocess.CompletedProcess:\n",
    "    \"\"\"\n",
    "    Since relative pathes are used in examples.\n",
    "    \"\"\"\n",
    "    cwd = py_file.parent\n",
    "    cmd = f\"python {py_file}\"\n",
    "    return subprocess.run(cmd, cwd=cwd, capture_output=True, check=True, shell=True, universal_newlines=True, text=True, timeout=30)\n",
    "\n",
    "def execute_wasm(iwasm_bin: Path, wasm_file: Path) -> subprocess.CompletedProcess:\n",
    "    \"\"\"\n",
    "    To avoid the WASI pre-opens problem, run under the same directory with the wasm file\n",
    "    \"\"\"\n",
    "    cwd = wasm_file.parent\n",
    "    # stack: 128M  pre-open: PWD\n",
    "    cmd = f\"{iwasm_bin} --dir=. --stack-size=134217728 {wasm_file.relative_to(cwd)}\"\n",
    "    return subprocess.run(cmd, cwd=cwd, capture_output=True, check=True, shell=True, universal_newlines=True, text=True, timeout=80)\n",
    "    \n",
    "\n",
    "def compare_result(expected: str, actual: str) -> bool:\n",
    "    return expected == actual\n",
    "\n",
    "##################################################\n",
    "def execute_case(py_file: Path, out_dir: Optional[Path]) -> CaseResult:\n",
    "    ## execute python firstly to avoid un-necessary wasm compilation\n",
    "    try:\n",
    "        p = execute_py(py_file)\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        return CaseResult(CaseErrorCode.PY_EXECUTION_FAILURE, e.stderr if e.stderr else e.stdout)\n",
    "    except subprocess.TimeoutExpired as e:\n",
    "        return CaseResult(CaseErrorCode.PY_EXECUTION_TIMEOUT, e.stderr if e.stderr else e.stdout)\n",
    "    output_from_py = p.stdout\n",
    "\n",
    "    try:\n",
    "        wasm_file = compile_py_2_wasm(PY2WASM, py_file, out_dir)\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        return CaseResult(CaseErrorCode.COMPILATION_FAILURE, e.stderr if e.stderr else e.stdout)\n",
    "    except subprocess.TimeoutExpired as e:\n",
    "        return CaseResult(CaseErrorCode.COMPILATION_FAILURE, e.stderr if e.stderr else e.stdout)\n",
    "\n",
    "    try:\n",
    "        p = execute_wasm(IWASM, wasm_file)\n",
    "    except subprocess.CalledProcessError as e:\n",
    "        return CaseResult(CaseErrorCode.WASM_EXECUTION_FAILURE, f\"{e.stderr}\\n{e.stdout}\")\n",
    "    except subprocess.TimeoutExpired as e:\n",
    "        return CaseResult(CaseErrorCode.WASM_EXECUTION_TIMEOUT, f\"{e.stderr}\\n{e.stdout}\")\n",
    "    output_from_wasm = p.stdout\n",
    "\n",
    "    if not compare_result(output_from_py, output_from_wasm):\n",
    "        return CaseResult(CaseErrorCode.DIFFERENT_RESULT, f\"{'>' * 40}\\n{output_from_py}{'-' * 20} V.S. {'-' * 20}\\n{output_from_wasm}{'<' * 40}\")\n",
    "    \n",
    "    return CaseResult(CaseErrorCode.OK, \"\")\n",
    "\n",
    "def visit_case(py_file: Path, out_dir: Optional[Path]) -> CaseResult:\n",
    "    print(f\"py_file={py_file}, out_dir={out_dir}\")\n",
    "    return CaseResult(CaseErrorCode.OK, \"\")\n",
    "\n",
    "def execute_test(chapter: Path, bypass: List[str]) -> Dict[str, CaseResult]:\n",
    "    # list all sub-directories in chapter\n",
    "    chapter_tests = [x for x in chapter.iterdir() if x.is_dir()]\n",
    "\n",
    "    # walk\n",
    "    ret = {}\n",
    "    for test_dir in tqdm(chapter_tests):\n",
    "        # assume all .py under the test_dir are test cases\n",
    "        py_files = [x for x in test_dir.iterdir() if x.suffix == \".py\"]\n",
    "\n",
    "        for py_file in py_files:\n",
    "            case_name = f\"{test_dir.name}.{py_file.stem}\"\n",
    "\n",
    "            if case_name in bypass:\n",
    "                ret[case_name] = CaseResult(CaseErrorCode.BYPASS, \"\")\n",
    "                continue\n",
    "\n",
    "            result = execute_case(py_file, None)\n",
    "            #result = visit_case(py_file, None)\n",
    "            ret[case_name] = result \n",
    "    \n",
    "    return ret\n",
    "\n",
    "def summarize_result(results: Dict[str, CaseResult]) -> None:\n",
    "    counter = Counter([x.error_code for x in results.values()])\n",
    "    print()\n",
    "    print(counter)\n",
    "    print()\n",
    "\n",
    "    # print failures\n",
    "    for k,v in results.items():\n",
    "        if v.error_code != CaseErrorCode.OK:\n",
    "            print(f\"{k} FAILED:\\n{v}\")\n",
    "            print()\n",
    "\n",
    "def stash_result(results: Dict[str, CaseResult], out_file: Path) -> None:\n",
    "    with out_file.open(\"wb\") as f:\n",
    "        pickle.dump(results, f)\n",
    "\n",
    "def restore_result(out_file: Path) -> Dict[str, CaseResult]:\n",
    "    with out_file.open(\"rb\") as f:\n",
    "        return pickle.load(f)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Bypass\n",
    "\n",
    "Bypass some cases that are not supported by the current implementation.\n",
    "- `socket`. because there is no official support for socket in wasi-libc. *wasip1*\n",
    "- `subproess`. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# find . -name \"*.py\" -type f | xargs grep -rin \"socket\" | awk -F':' '{print $1}' | sort | uniq\n",
    "SOCKET_INVOLVED_CASES = {\n",
    "    \"5\": [\n",
    "        \"wrapping_an_existing_file_descriptor_as_a_file_object.echo\",\n",
    "    ],\n",
    "    \"7\": [\n",
    "        \"making_an_n-argument_callable_work_as_a_callable_with_fewer_arguments.example3\",\n",
    "    ],\n",
    "    \"8\": [\n",
    "        \"how_to_define_an_interface_or_abstract_base_class.example\",\n",
    "        \"making_objects_support_the_context_manager_protocol.example1\",\n",
    "        \"making_objects_support_the_context_manager_protocol.example2\",\n",
    "    ],\n",
    "    \"11\": [\n",
    "        \"adding_ssl_to_network_servers.echoclient\",\n",
    "        \"adding_ssl_to_network_servers.echoserv\",\n",
    "        \"adding_ssl_to_network_servers.sslmixin\",\n",
    "        \"creating_a_tcp_server.echoclient\",\n",
    "        \"creating_a_tcp_server.echoserv\",\n",
    "        \"creating_a_tcp_server.echoserv1\",\n",
    "        \"creating_a_tcp_server.echoserv2\",\n",
    "        \"creating_a_tcp_server.echoserv3\",\n",
    "        \"creating_a_tcp_server.echoserv4\",\n",
    "        \"creating_a_tcp_server.echoserv5\",\n",
    "        \"creating_a_tcp_server.threadedserv\",\n",
    "        \"creating_a_udp_server.client\",\n",
    "        \"creating_a_udp_server.timeserv1\",\n",
    "        \"creating_a_udp_server.timeserv2\",\n",
    "        \"event_driven_io_explained.tcpclient\",\n",
    "        \"event_driven_io_explained.tcpserver\",\n",
    "        \"event_driven_io_explained.threadpool\",\n",
    "        \"event_driven_io_explained.thrpoolclient\",\n",
    "        \"event_driven_io_explained.udpclient\",\n",
    "        \"event_driven_io_explained.udpserver\",\n",
    "        \"passing_a_socket_file_descriptor_between_processes.client1\",\n",
    "        \"passing_a_socket_file_descriptor_between_processes.server\",\n",
    "        \"passing_a_socket_file_descriptor_between_processes.server1\",\n",
    "        \"passing_a_socket_file_descriptor_between_processes.servermp\",\n",
    "        \"passing_a_socket_file_descriptor_between_processes.worker\",\n",
    "        \"passing_a_socket_file_descriptor_between_processes.workermp\",\n",
    "        \"simple_authentication_of_clients.client\",\n",
    "        \"simple_authentication_of_clients.server\",\n",
    "        \"zero_copy_sending_and_receiving_of_large_arrays.client\",\n",
    "        \"zero_copy_sending_and_receiving_of_large_arrays.server\",\n",
    "    ],\n",
    "    \"12\": [\n",
    "        \"how_to_create_a_thread_pool.example1\",\n",
    "        \"how_to_create_a_thread_pool.example2\",\n",
    "        \"polling_multiple_thread_queues.pqueue\",\n",
    "        \"storing_thread_specific_state.example1\",\n",
    "        \"storing_thread_specific_state.example2\",\n",
    "        \"using_generators_as_an_alternative_to_threads.netsched\",\n",
    "    ],\n",
    "    \"13\": [\n",
    "        \"generating_a_range_of_ip_addresses_from_a_cidr_address.example\"\n",
    "    ]\n",
    "}\n",
    "\n",
    "# find . -name \"*.py\" -type f | xargs grep -rin \"subprocess\" | awk -F':' '{print $1}' | sort | uniq\n",
    "SUBPROCESS_INVOLVED_CASES = {\n",
    "    \"13\": [\n",
    "        \"executing_an_external_command_and_getting_its_output.example1\",\n",
    "        \"executing_an_external_command_and_getting_its_output.example2\"\n",
    "    ]\n",
    "}\n",
    "\n",
    "# find . -name \"*.py\" -type f | xargs grep -rin \"multiprocess\" | awk -F':' '{print $1}' | sort | uniq\n",
    "MULTIPROCESS_INVOLVED_CASES = {\n",
    "    \"7\": [\n",
    "        \"inlining_callback_functions.example\",\n",
    "        \"making_an_n-argument_callable_work_as_a_callable_with_fewer_arguments.example2\"\n",
    "    ],\n",
    "    \"11\": [\n",
    "        \"implementing_remote_procedure_call.jsonrpclient\",\n",
    "        \"implementing_remote_procedure_call.jsonrpcserver\",\n",
    "        \"implementing_remote_procedure_call.rpcclient\",\n",
    "        \"implementing_remote_procedure_call.rpcserver\",\n",
    "        \"passing_a_socket_file_descriptor_between_processes.server1\",\n",
    "        \"passing_a_socket_file_descriptor_between_processes.servermp\",\n",
    "        \"passing_a_socket_file_descriptor_between_processes.workermp\",\n",
    "        \"simple_communication_between_interpreters.echoclient\",\n",
    "        \"simple_communication_between_interpreters.echoserv\",\n",
    "    ]\n",
    "}\n",
    "\n",
    "def get_ignore_list(N: str) -> List[str]:\n",
    "    \"\"\"\n",
    "    ZZZ_CASE.extend(XXX_CASE).extend(YYY_CASE)\n",
    "    \"\"\"\n",
    "    return SOCKET_INVOLVED_CASES.get(N, []) \\\n",
    "        + SUBPROCESS_INVOLVED_CASES.get(N, []) \\\n",
    "        + MULTIPROCESS_INVOLVED_CASES.get(N, [])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 1. Data Structures And Algorithms\n",
    "\n",
    "`DIFFERENT_RESULT` of _finding_out_what_two_dictionaries_have_in_common_ isn't a bug 😄. It is caused by the different order of the keys in the dictionary.\n",
    "\n",
    "`EXECUTION_FAILURE` of _transforming_and_reducing_data_at_the_same_time_ is a requestd feature that isn't supported by the current implementation of WAMR\n",
    "\n",
    "---\n",
    "\n",
    "**AR ✨**\n",
    "\n",
    "- [ ] WAMR needs to support `~`, `.`, `..`\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 16/16 [05:12<00:00, 19.56s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 15, <CaseErrorCode.DIFFERENT_RESULT: 4>: 1, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 1})\n",
      "\n",
      "finding_out_what_two_dictionaries_have_in_common.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "Common keys: {'y', 'x'}\n",
      "Keys in a not in b: {'z'}\n",
      "(key,value) pairs in common: {('y', 2)}\n",
      "-------------------- V.S. --------------------\n",
      "Common keys: {'x', 'y'}\n",
      "Keys in a not in b: {'z'}\n",
      "(key,value) pairs in common: {('y', 2)}\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "transforming_and_reducing_data_at_the_same_time.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 6, in <module>\n",
      "    files = os.listdir(os.path.expanduser('~'))\n",
      "    \n",
      "FileNotFoundError: [Errno 44] No such file or directory: '~'\n",
      "\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_1 = PYTHON_COOKBOOK.joinpath(\"1\")\n",
    "chapter_1_result = execute_test(chapter_1, get_ignore_list(\"1\"))\n",
    "summarize_result(chapter_1_result)\n",
    "stash_result(chapter_1_result, Path(\"chapter_1_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 2. Strings And Text\n",
    "\n",
    "There are `try...except...` in some cases. Need to deep dive into the wasm implementation.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 13/13 [04:19<00:00, 19.97s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 15})\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_2 = PYTHON_COOKBOOK.joinpath(\"2\")\n",
    "chapter_2_result = execute_test(chapter_2, get_ignore_list(\"2\"))\n",
    "summarize_result(chapter_2_result)\n",
    "stash_result(chapter_2_result, Path(\"chapter_2_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 3. Numbers, Dates, And Times\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 2/2 [00:34<00:00, 17.07s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 2})\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_3 = PYTHON_COOKBOOK.joinpath(\"3\")\n",
    "chapter_3_result = execute_test(chapter_3, get_ignore_list(\"3\"))\n",
    "summarize_result(chapter_3_result)\n",
    "stash_result(chapter_3_result, Path(\"chapter_3_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 4. Iterators And Generators\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 10/10 [02:26<00:00, 14.64s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 9, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 1, <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 1})\n",
      "\n",
      "creating_data_processing_pipelines.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 3, in <module>\n",
      "    import gzip\n",
      "    \n",
      "  File \"./gzip.py\", line 9, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "\n",
      "how_to_flatten_a_nested_sequence.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/4/how_to_flatten_a_nested_sequence/example.py\", line 3, in <module>\n",
      "    from collections import Iterable\n",
      "ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/lib/python3.11/collections/__init__.py)\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_4 = PYTHON_COOKBOOK.joinpath(\"4\")\n",
    "chapter_4_result = execute_test(chapter_4, get_ignore_list(\"4\"))\n",
    "summarize_result(chapter_4_result)\n",
    "stash_result(chapter_4_result, Path(\"chapter_4_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 5. Files And I/O\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 6/6 [01:03<00:00, 10.65s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 4, <CaseErrorCode.BYPASS: 5>: 1, <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 1})\n",
      "\n",
      "wrapping_an_existing_file_descriptor_as_a_file_object.echo FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "adding_or_changing_the_encoding_of_an_already_open_file.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/5/adding_or_changing_the_encoding_of_an_already_open_file/example.py\", line 8, in <module>\n",
      "    text = f.read()\n",
      "           ^^^^^^^^\n",
      "  File \"<frozen codecs>\", line 322, in decode\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_5 = PYTHON_COOKBOOK.joinpath(\"5\")\n",
    "chapter_5_result = execute_test(chapter_5, get_ignore_list(\"5\"))\n",
    "summarize_result(chapter_5_result)\n",
    "stash_result(chapter_5_result, Path(\"chapter_5_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 6. Data Encoding And Processing\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 8/8 [03:52<00:00, 29.09s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 10, <CaseErrorCode.DIFFERENT_RESULT: 4>: 2, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 1, <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 1})\n",
      "\n",
      "reading_and_writing_json_data.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "OrderedDict([('name', 'ACME'), ('shares', 50), ('price', 490.1)])\n",
      "ACME\n",
      "50\n",
      "490.1\n",
      "{\"__classname__\": \"Point\", \"x\": 3, \"y\": 4}\n",
      "<__main__.Point object at 0x7f38b35028d0>\n",
      "3\n",
      "4\n",
      "-------------------- V.S. --------------------\n",
      "OrderedDict([('name', 'ACME'), ('shares', 50), ('price', 490.1)])\n",
      "ACME\n",
      "50\n",
      "490.1\n",
      "{\"__classname__\": \"Point\", \"x\": 3, \"y\": 4}\n",
      "<__main__.Point object at 0x9dc3a0>\n",
      "3\n",
      "4\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "parsing_xml_documents_with_namespaces.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "<Element '{http://www.w3.org/1999/xhtml}html' at 0x7fa2c83fcfe0>\n",
      "Hello World\n",
      "-------------------- V.S. --------------------\n",
      "<Element '{http://www.w3.org/1999/xhtml}html' at 0xc776b8>\n",
      "Hello World\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "parsing_simple_xml_data.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1437, in _path_importer_cache\n",
      "KeyError: './email'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 1, in <module>\n",
      "    from urllib.request import urlopen\n",
      "    \n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./urllib/request.py\", line 88, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./http/client.py\", line 72, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1138, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 1078, in _find_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1504, in find_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1473, in _get_spec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1439, in _path_importer_cache\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 1415, in _path_hooks\n",
      "  File \"./posixpath.py\", line 399, in abspath\n",
      "UnboundLocalError: cannot access local variable 'path' where it is not associated with a value\n",
      "\n",
      "\n",
      "\n",
      "parsing_modifying_and_rewriting_xml.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/6/parsing_modifying_and_rewriting_xml/example.py\", line 14, in <module>\n",
      "    nm_index = root.getchildren().index(root.find('nm'))\n",
      "               ^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_6 = PYTHON_COOKBOOK.joinpath(\"6\")\n",
    "chapter_6_result = execute_test(chapter_6, get_ignore_list(\"6\"))\n",
    "summarize_result(chapter_6_result)\n",
    "stash_result(chapter_6_result, Path(\"chapter_6_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 7. Functions\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 7/7 [02:13<00:00, 19.09s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 6, <CaseErrorCode.BYPASS: 5>: 3, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 2})\n",
      "\n",
      "inlining_callback_functions.example FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "making_an_n-argument_callable_work_as_a_callable_with_fewer_arguments.example2 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "making_an_n-argument_callable_work_as_a_callable_with_fewer_arguments.example3 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "accessing_variables_defined_inside_a_closure.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example2.py\", line 34, in <module>\n",
      "    s.push(10)\n",
      "\n",
      "AttributeError: 'ClosureInstance' object has no attribute 'push'\n",
      "\n",
      "<__main__.ClosureInstance object at 0xaa0be0>\n",
      "\n",
      "\n",
      "accessing_variables_defined_inside_a_closure.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example3.py\", line 27, in <module>\n",
      "    print(timeit('s.push(1); s.pop()', 'from __main__ import s'))\n",
      "\n",
      "  File \"./timeit.py\", line 237, in timeit\n",
      "  File \"./timeit.py\", line 180, in timeit\n",
      "  File \"<timeit-src>\", line 6, in inner\n",
      "AttributeError: 'ClosureInstance' object has no attribute 'push'\n",
      "\n",
      "Using a class\n",
      "9.727151817991398\n",
      "Using a closure\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_7 = PYTHON_COOKBOOK.joinpath(\"7\")\n",
    "chapter_7_result = execute_test(chapter_7, get_ignore_list(\"7\"))\n",
    "summarize_result(chapter_7_result)\n",
    "stash_result(chapter_7_result, Path(\"chapter_7_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 8. Classes And Objects\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 24/24 [12:31<00:00, 31.30s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 40, <CaseErrorCode.BYPASS: 5>: 3, <CaseErrorCode.DIFFERENT_RESULT: 4>: 3, <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 2, <CaseErrorCode.WASM_EXECUTION_TIMEOUT: 6>: 1})\n",
      "\n",
      "making_objects_support_the_context_manager_protocol.example2 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "making_objects_support_the_context_manager_protocol.example1 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "implementing_the_visitor_pattern_without_recursion.example1 FAILED:\n",
      "WASM_EXECUTION_TIMEOUT\n",
      "None\n",
      "None\n",
      "\n",
      "how_to_define_an_interface_or_abstract_base_class.example FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_an_instance_without_invoking_init.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "<__main__.Date object at 0x7fb832d87390>\n",
      "False\n",
      "2012\n",
      "8\n",
      "2024 7 27\n",
      "-------------------- V.S. --------------------\n",
      "<__main__.Date object at 0x8597f0>\n",
      "False\n",
      "2012\n",
      "8\n",
      "2024 7 27\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "implementing_stateful_objects_or_state_machines.example2 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "<__main__.Connection object at 0x7f12eecfd190>\n",
      "Not open\n",
      "<__main__.Connection object at 0x7f12eecfd190>\n",
      "reading\n",
      "<__main__.Connection object at 0x7f12eecfd190>\n",
      "-------------------- V.S. --------------------\n",
      "<__main__.Connection object at 0xaa57d0>\n",
      "Not open\n",
      "<__main__.Connection object at 0xaa57d0>\n",
      "reading\n",
      "<__main__.Connection object at 0xaa57d0>\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "implementing_stateful_objects_or_state_machines.example1 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "<__main__.ClosedConnection object at 0x7f8b4e0df6d0>\n",
      "Not open\n",
      "<__main__.OpenConnection object at 0x7f8b4e0df6d0>\n",
      "reading\n",
      "<__main__.ClosedConnection object at 0x7f8b4e0df6d0>\n",
      "-------------------- V.S. --------------------\n",
      "<__main__.ClosedConnection object at 0xaa1f40>\n",
      "Not open\n",
      "<__main__.OpenConnection object at 0xaa1f40>\n",
      "reading\n",
      "<__main__.ClosedConnection object at 0xaa1f40>\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "implementing_custom_containers.example2 FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/8/implementing_custom_containers/example2.py\", line 3, in <module>\n",
      "    class Items(collections.MutableSequence):\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: module 'collections' has no attribute 'MutableSequence'\n",
      "\n",
      "\n",
      "implementing_custom_containers.example1 FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/8/implementing_custom_containers/example1.py\", line 6, in <module>\n",
      "    class SortedItems(collections.Sequence):\n",
      "                      ^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: module 'collections' has no attribute 'Sequence'\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_8 = PYTHON_COOKBOOK.joinpath(\"8\")\n",
    "chapter_8_result = execute_test(chapter_8, get_ignore_list(\"8\"))\n",
    "summarize_result(chapter_8_result)\n",
    "stash_result(chapter_8_result, Path(\"chapter_8_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 9. Metaprogramming\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 23/23 [09:26<00:00, 24.64s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 22, <CaseErrorCode.DIFFERENT_RESULT: 4>: 10, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 2, <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 2})\n",
      "\n",
      "preserving_function_metadata_when_writing_decorators.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "countdown 0.0022516250610351562\n",
      "Name: countdown\n",
      "Docstring: '\\n        Counts down\\n        '\n",
      "Annotations: {'n': <class 'int'>}\n",
      "-------------------- V.S. --------------------\n",
      "countdown 0.008459806442260742\n",
      "Name: countdown\n",
      "Docstring: '\\n        Counts down\\n        '\n",
      "Annotations: {'n': <class 'int'>}\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "defining_decorators_as_classes.example2 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "5\n",
      "9\n",
      "ncalls: 2\n",
      "<__main__.Spam object at 0x7f5893afee10> 1\n",
      "<__main__.Spam object at 0x7f5893afee10> 2\n",
      "<__main__.Spam object at 0x7f5893afee10> 3\n",
      "ncalls: 3\n",
      "-------------------- V.S. --------------------\n",
      "5\n",
      "9\n",
      "ncalls: 2\n",
      "<__main__.Spam object at 0xbf1a20> 1\n",
      "<__main__.Spam object at 0xbf1a20> 2\n",
      "<__main__.Spam object at 0xbf1a20> 3\n",
      "ncalls: 3\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "defining_decorators_as_classes.example1 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "5\n",
      "9\n",
      "ncalls: 2\n",
      "<__main__.Spam object at 0x7f7f1a467e90> 1\n",
      "<__main__.Spam object at 0x7f7f1a467e90> 2\n",
      "<__main__.Spam object at 0x7f7f1a467e90> 3\n",
      "ncalls: 3\n",
      "-------------------- V.S. --------------------\n",
      "5\n",
      "9\n",
      "ncalls: 2\n",
      "<__main__.Spam object at 0xbf6470> 1\n",
      "<__main__.Spam object at 0xbf6470> 2\n",
      "<__main__.Spam object at 0xbf6470> 3\n",
      "ncalls: 3\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "defining_decorators_as_classes.example3 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "5\n",
      "9\n",
      "ncalls: 2\n",
      "<__main__.Spam object at 0x7ffb2d52ae90> 1\n",
      "<__main__.Spam object at 0x7ffb2d52ae90> 2\n",
      "<__main__.Spam object at 0x7ffb2d52ae90> 3\n",
      "ncalls: 3\n",
      "countdown 0.002207040786743164\n",
      "countdown 0.22380828857421875\n",
      "2\n",
      "-------------------- V.S. --------------------\n",
      "5\n",
      "9\n",
      "ncalls: 2\n",
      "<__main__.Spam object at 0xbf4250> 1\n",
      "<__main__.Spam object at 0xbf4250> 2\n",
      "<__main__.Spam object at 0xbf4250> 3\n",
      "ncalls: 3\n",
      "countdown 0.010495901107788086\n",
      "countdown 1.0506184101104736\n",
      "2\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "disassembling_python_byte_code.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 30, in <module>\n",
      "    for op, oparg in generate_opcodes(countdown.__code__.co_code):\n",
      "    \n",
      "  File \"./example.py\", line 13, in generate_opcodes\n",
      "    oparg = codebytes[i] + codebytes[i+1]*256 + extended_arg\n",
      "\n",
      "IndexError: index out of range\n",
      "\n",
      "151 RESUME 29696\n",
      "1 POP_TOP None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "100 LOAD_CONST 42497\n",
      "1 POP_TOP None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "171 CALL 1\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "0 CACHE None\n",
      "\n",
      "\n",
      "defining_classes_programmatically.example1 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "<types.Stock object at 0x7f086fb8b550>\n",
      "4555.0\n",
      "-------------------- V.S. --------------------\n",
      "<types.Stock object at 0xbf40e0>\n",
      "4555.0\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "applying_decorators_to_class_and_static_methods.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "<__main__.Spam object at 0x7f1b6b3bb6d0> 10000000\n",
      "0.22405791282653809\n",
      "<class '__main__.Spam'> 10000000\n",
      "0.22251248359680176\n",
      "10000000\n",
      "0.2238786220550537\n",
      "-------------------- V.S. --------------------\n",
      "<__main__.Spam object at 0xbf6060> 10000000\n",
      "1.3193109035491943\n",
      "<class '__main__.Spam'> 10000000\n",
      "1.3221008777618408\n",
      "10000000\n",
      "1.3535828590393066\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "defining_a_decorator_with_user_adjustable_attributes.example1 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "5\n",
      "5\n",
      "5\n",
      "countdown 0.0021715164184570312\n",
      "countdown 0.0021567344665527344\n",
      "countdown2 0.0021524429321289062\n",
      "countdown2 0.0021300315856933594\n",
      "-------------------- V.S. --------------------\n",
      "5\n",
      "5\n",
      "5\n",
      "countdown 0.013771772384643555\n",
      "countdown 0.013826847076416016\n",
      "countdown2 0.013441801071166992\n",
      "countdown2 0.013458728790283203\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "capturing_class_attribute_definition_order.example2 FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/9/capturing_class_attribute_definition_order/example2.py\", line 25, in <module>\n",
      "    class A(metaclass=OrderedMeta):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/9/capturing_class_attribute_definition_order/example2.py\", line 30, in A\n",
      "    def spam(self):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/9/capturing_class_attribute_definition_order/example2.py\", line 11, in __setitem__\n",
      "    raise TypeError('{} already defined in {}'.format(name, self.clsname))\n",
      "TypeError: spam already defined in A\n",
      "\n",
      "\n",
      "parsing_and_analyzing_python_source.example1 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "Loaded: {'range', 'print', 'i'}\n",
      "Stored: {'i'}\n",
      "Deleted: {'i'}\n",
      "-------------------- V.S. --------------------\n",
      "Loaded: {'print', 'range', 'i'}\n",
      "Stored: {'i'}\n",
      "Deleted: {'i'}\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "parsing_and_analyzing_python_source.namelower FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./namelower.py\", line 60, in <module>\n",
      "    @lower_names('INCR')\n",
      "    \n",
      "  File \"./namelower.py\", line 49, in lower\n",
      "    func.__code__ = temp[func.__name__].__code__\n",
      "\n",
      "KeyError: 'countdown2'\n",
      "\n",
      "\n",
      "\n",
      "enforcing_coding_conventions_in_classes.example1 FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/9/enforcing_coding_conventions_in_classes/example1.py\", line 18, in <module>\n",
      "    class B(Root):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/9/enforcing_coding_conventions_in_classes/example1.py\", line 7, in __new__\n",
      "    raise TypeError('Bad attribute name: ' + name)\n",
      "TypeError: Bad attribute name: fooBar\n",
      "\n",
      "\n",
      "defining_context_managers_the_easy_way.example1 FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "counting: 0.3920738697052002\n",
      "-------------------- V.S. --------------------\n",
      "counting: 2.520106077194214\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "executing_code_with_local_side_effects.example FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      ":::: Running test()\n",
      "14\n",
      ":::: Running test1()\n",
      "0\n",
      ":::: Running test2()\n",
      "before: {'x': 0}\n",
      "after: {'x': 1, 'loc': {...}}\n",
      "x = 0\n",
      ":::: Running test3()\n",
      "{'x': 0}\n",
      "{'x': 1, 'loc': {...}}\n",
      "{'x': 0, 'loc': {...}}\n",
      ":::: Running test4()\n",
      "14\n",
      "-------------------- V.S. --------------------\n",
      ":::: Running test()\n",
      "14\n",
      ":::: Running test1()\n",
      "0\n",
      ":::: Running test2()\n",
      "before: {'x': 0}\n",
      "after: {'x': 1, 'loc': {...}}\n",
      "x = 0\n",
      ":::: Running test3()\n",
      "{'x': 0}\n",
      "{'x': 1, 'loc': {...}}\n",
      "{'x': 1, 'loc': {...}}\n",
      ":::: Running test4()\n",
      "14\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_9 = PYTHON_COOKBOOK.joinpath(\"9\")\n",
    "chapter_9_result = execute_test(chapter_9, get_ignore_list(\"9\"))\n",
    "summarize_result(chapter_9_result)\n",
    "stash_result(chapter_9_result, Path(\"chapter_9_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 10. Modules And Packages\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 4/4 [01:40<00:00, 25.11s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 5, <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 3, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 1})\n",
      "\n",
      "loading_modules_from_a_remote_machine_using_import_hooks.metaexample FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/10/loading_modules_from_a_remote_machine_using_import_hooks/metaexample.py\", line 13, in <module>\n",
      "    import fib\n",
      "ModuleNotFoundError: No module named 'fib'\n",
      "\n",
      "\n",
      "loading_modules_from_a_remote_machine_using_import_hooks.pathexample FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/10/loading_modules_from_a_remote_machine_using_import_hooks/pathexample.py\", line 14, in <module>\n",
      "    import fib\n",
      "ModuleNotFoundError: No module named 'fib'\n",
      "\n",
      "\n",
      "loading_modules_from_a_remote_machine_using_import_hooks.urlimport FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "./urlimport.py:5: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses\n",
      "  import imp\n",
      "Traceback (most recent call last):\n",
      "  File \"./urlimport.py\", line 6, in <module>\n",
      "    from urllib.request import urlopen\n",
      "    \n",
      "  File \"./urllib/request.py\", line 88, in <module>\n",
      "  File \"./http/client.py\", line 72, in <module>\n",
      "ModuleNotFoundError: No module named 'email.message'\n",
      "\n",
      "Exception: out of bounds memory access\n",
      "\n",
      "\n",
      "loading_modules_from_a_remote_machine_using_import_hooks.explicit_load FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "/workspaces/wamr-with-py/cookbook/src/10/loading_modules_from_a_remote_machine_using_import_hooks/explicit_load.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses\n",
      "  import imp\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 1348, in do_open\n",
      "    h.request(req.get_method(), req.selector, req.data, headers,\n",
      "  File \"/usr/local/lib/python3.11/http/client.py\", line 1303, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/usr/local/lib/python3.11/http/client.py\", line 1349, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/usr/local/lib/python3.11/http/client.py\", line 1298, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/usr/local/lib/python3.11/http/client.py\", line 1058, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/usr/local/lib/python3.11/http/client.py\", line 996, in send\n",
      "    self.connect()\n",
      "  File \"/usr/local/lib/python3.11/http/client.py\", line 962, in connect\n",
      "    self.sock = self._create_connection(\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/socket.py\", line 851, in create_connection\n",
      "    raise exceptions[0]\n",
      "  File \"/usr/local/lib/python3.11/socket.py\", line 836, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/10/loading_modules_from_a_remote_machine_using_import_hooks/explicit_load.py\", line 18, in <module>\n",
      "    fib = load_module('http://localhost:15000/fib.py')\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/10/loading_modules_from_a_remote_machine_using_import_hooks/explicit_load.py\", line 8, in load_module\n",
      "    u = urllib.request.urlopen(url)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 216, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 519, in open\n",
      "    response = self._open(req, data)\n",
      "               ^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 536, in _open\n",
      "    result = self._call_chain(self.handle_open, protocol, protocol +\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 1377, in http_open\n",
      "    return self.do_open(http.client.HTTPConnection, req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 1351, in do_open\n",
      "    raise URLError(err)\n",
      "urllib.error.URLError: <urlopen error [Errno 111] Connection refused>\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_10 = PYTHON_COOKBOOK.joinpath(\"10\")\n",
    "chapter_10_result = execute_test(chapter_10, get_ignore_list(\"10\"))\n",
    "summarize_result(chapter_10_result)\n",
    "stash_result(chapter_10_result, Path(\"chapter_10_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 11. Network And Web Programming"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 12/12 [04:48<00:00, 24.01s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.BYPASS: 5>: 36, <CaseErrorCode.OK: 0>: 4, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 4, <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 3, <CaseErrorCode.PY_EXECUTION_TIMEOUT: 7>: 3})\n",
      "\n",
      "event_driven_io_explained.tcpclient FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "event_driven_io_explained.threadpool FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "event_driven_io_explained.udpclient FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "event_driven_io_explained.thrpoolclient FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "event_driven_io_explained.tcpserver FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "event_driven_io_explained.udpserver FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "interacting_with_http_services_as_a_client.example4 FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/11/interacting_with_http_services_as_a_client/example4.py\", line 8, in <module>\n",
      "    last_modified =\tresp.headers['last-modified']\n",
      "                    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/vscode/.local/lib/python3.11/site-packages/requests/structures.py\", line 52, in __getitem__\n",
      "    return self._store[key.lower()][1]\n",
      "           ~~~~~~~~~~~^^^^^^^^^^^^^\n",
      "KeyError: 'last-modified'\n",
      "\n",
      "\n",
      "interacting_with_http_services_as_a_client.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "\n",
      "Exception: out of bounds memory access\n",
      "\n",
      "\n",
      "interacting_with_http_services_as_a_client.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "\n",
      "Exception: out of bounds memory access\n",
      "\n",
      "\n",
      "interacting_with_http_services_as_a_client.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "\n",
      "Exception: out of bounds memory access\n",
      "\n",
      "\n",
      "creating_a_udp_server.timeserv1 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_udp_server.client FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_udp_server.timeserv2 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "simple_authentication_of_clients.server FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "simple_authentication_of_clients.client FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "simple_remote_procedure_call_with_xmlrpc.keyserv FAILED:\n",
      "PY_EXECUTION_TIMEOUT\n",
      "None\n",
      "\n",
      "simple_remote_procedure_call_with_xmlrpc.client FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/11/simple_remote_procedure_call_with_xmlrpc/client.py\", line 3, in <module>\n",
      "    s.set('foo', 'bar')\n",
      "  File \"/usr/local/lib/python3.11/xmlrpc/client.py\", line 1122, in __call__\n",
      "    return self.__send(self.__name, args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/xmlrpc/client.py\", line 1464, in __request\n",
      "    response = self.__transport.request(\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/xmlrpc/client.py\", line 1166, in request\n",
      "    return self.single_request(host, handler, request_body, verbose)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/xmlrpc/client.py\", line 1179, in single_request\n",
      "    resp = http_conn.getresponse()\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/http/client.py\", line 1395, in getresponse\n",
      "    response.begin()\n",
      "  File \"/usr/local/lib/python3.11/http/client.py\", line 325, in begin\n",
      "    version, status, reason = self._read_status()\n",
      "                              ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/http/client.py\", line 286, in _read_status\n",
      "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/socket.py\", line 706, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ConnectionResetError: [Errno 104] Connection reset by peer\n",
      "\n",
      "\n",
      "implementing_remote_procedure_call.rpcserver FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "implementing_remote_procedure_call.rpcclient FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "implementing_remote_procedure_call.jsonrpcserver FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "implementing_remote_procedure_call.jsonrpclient FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "simple_communication_between_interpreters.echoclient FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "simple_communication_between_interpreters.echoserv FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.servermp FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.workermp FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.server FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.client1 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.server1 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "passing_a_socket_file_descriptor_between_processes.worker FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_simple_rest_based_interface.example1 FAILED:\n",
      "PY_EXECUTION_TIMEOUT\n",
      "b'Serving on port 8080...\\n'\n",
      "\n",
      "creating_a_simple_rest_based_interface.client1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./client1.py\", line 1, in <module>\n",
      "    from urllib.request import urlopen\n",
      "    \n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./urllib/request.py\", line 88, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1147, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n",
      "  File \"./http/client.py\", line 72, in <module>\n",
      "  File \"<frozen importlib._bootstrap>\", line 1176, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 1138, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 1078, in _find_spec\n",
      "TypeError: '' object is not callable\n",
      "\n",
      "\n",
      "\n",
      "adding_ssl_to_network_servers.echoclient FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "adding_ssl_to_network_servers.ssl_xmlrpc_server FAILED:\n",
      "PY_EXECUTION_TIMEOUT\n",
      "None\n",
      "\n",
      "adding_ssl_to_network_servers.sslmixin FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "adding_ssl_to_network_servers.echoserv FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "adding_ssl_to_network_servers.ssl_xmlrpc_client FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "/workspaces/wamr-with-py/cookbook/src/11/adding_ssl_to_network_servers/ssl_xmlrpc_client.py:11: DeprecationWarning: ssl.PROTOCOL_TLSv1 is deprecated\n",
      "  self._ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/11/adding_ssl_to_network_servers/ssl_xmlrpc_client.py\", line 24, in <module>\n",
      "    transport=VerifyCertSafeTransport('server_cert.pem', 'client_cert.pem', 'client_key.pem'),\n",
      "              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/11/adding_ssl_to_network_servers/ssl_xmlrpc_client.py\", line 12, in __init__\n",
      "    self._ssl_context.load_verify_locations(cafile)\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "\n",
      "\n",
      "zero_copy_sending_and_receiving_of_large_arrays.server FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "zero_copy_sending_and_receiving_of_large_arrays.client FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoclient FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_tcp_server.threadedserv FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv2 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv5 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv4 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv3 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "creating_a_tcp_server.echoserv1 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_11 = PYTHON_COOKBOOK.joinpath(\"11\")\n",
    "chapter_11_result = execute_test(chapter_11, get_ignore_list(\"11\"))\n",
    "summarize_result(chapter_11_result)\n",
    "stash_result(chapter_11_result, Path(\"chapter_11_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 12. Concurrency\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 13/13 [07:59<00:00, 36.86s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 10, <CaseErrorCode.BYPASS: 5>: 6, <CaseErrorCode.OK: 0>: 5, <CaseErrorCode.PY_EXECUTION_TIMEOUT: 7>: 5, <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 2})\n",
      "\n",
      "how_to_start_and_stop_threads.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example.py\", line 19, in <module>\n",
      "    t.start()\n",
      "    \n",
      "  File \"./threading.py\", line 964, in start\n",
      "RuntimeError: can't start new thread\n",
      "\n",
      "\n",
      "\n",
      "defining_an_actor_task.actor FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./actor.py\", line 70, in <module>\n",
      "    p.start()\n",
      "\n",
      "  File \"./actor.py\", line 40, in start\n",
      "    t.start()\n",
      "\n",
      "  File \"./threading.py\", line 964, in start\n",
      "RuntimeError: can't start new thread\n",
      "\n",
      "\n",
      "\n",
      "defining_an_actor_task.tagged FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./tagged.py\", line 19, in <module>\n",
      "    a.start()\n",
      "\n",
      "  File \"./actor.py\", line 40, in start\n",
      "    t.start()\n",
      "\n",
      "  File \"./threading.py\", line 964, in start\n",
      "RuntimeError: can't start new thread\n",
      "\n",
      "\n",
      "\n",
      "defining_an_actor_task.worker FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./worker.py\", line 31, in <module>\n",
      "    worker.start()\n",
      "\n",
      "  File \"./actor.py\", line 40, in start\n",
      "    t.start()\n",
      "\n",
      "  File \"./threading.py\", line 964, in start\n",
      "RuntimeError: can't start new thread\n",
      "\n",
      "\n",
      "\n",
      "using_generators_as_an_alternative_to_threads.netsched FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "storing_thread_specific_state.example2 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "storing_thread_specific_state.example1 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "launching_a_daemon_process_on_unix.daemon FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Usage: /workspaces/wamr-with-py/cookbook/src/12/launching_a_daemon_process_on_unix/daemon.py [start|stop]\n",
      "\n",
      "\n",
      "how_to_determine_if_a_thread_has_started.example2 FAILED:\n",
      "PY_EXECUTION_TIMEOUT\n",
      "b'CountingT-minus  010\\n\\nT-minusCounting 1\\n 9\\nCounting 2\\nT-minus 8\\nCountingT-minus 7\\n 3\\nT-minusCounting 4 6\\n\\n'\n",
      "\n",
      "how_to_determine_if_a_thread_has_started.example1 FAILED:\n",
      "PY_EXECUTION_TIMEOUT\n",
      "b'Launching countdown\\ncountdown starting\\nT-minus 10\\ncountdown is running\\nT-minus 9\\nT-minus 8\\nT-minus 7\\nT-minus 6\\nT-minus 5\\n'\n",
      "\n",
      "how_to_determine_if_a_thread_has_started.example3 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example3.py\", line 17, in <module>\n",
      "    t.start()\n",
      "\n",
      "  File \"./threading.py\", line 964, in start\n",
      "RuntimeError: can't start new thread\n",
      "\n",
      "\n",
      "\n",
      "locking_with_deadlock_avoidance.example2 FAILED:\n",
      "PY_EXECUTION_TIMEOUT\n",
      "b'This program crashes with an exception. Press [return] to start'\n",
      "\n",
      "locking_with_deadlock_avoidance.example1 FAILED:\n",
      "PY_EXECUTION_TIMEOUT\n",
      "b'This program runs forever. Press [return] to start, Ctrl-C to exit'\n",
      "\n",
      "locking_with_deadlock_avoidance.example3 FAILED:\n",
      "PY_EXECUTION_TIMEOUT\n",
      "b\"/workspaces/wamr-with-py/cookbook/src/12/locking_with_deadlock_avoidance/example3.py:8: DeprecationWarning: currentThread() is deprecated, use current_thread() instead\\n  print(threading.currentThread(), 'eating')\\n\"\n",
      "\n",
      "how_to_lock_critical_sections.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example1.py\", line 36, in <module>\n",
      "    t1.start()\n",
      "\n",
      "  File \"./threading.py\", line 964, in start\n",
      "RuntimeError: can't start new thread\n",
      "\n",
      "\n",
      "\n",
      "polling_multiple_thread_queues.pqueue FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "how_to_communicate_between_threads.example2 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example2.py\", line 44, in <module>\n",
      "    t1.start()\n",
      "\n",
      "  File \"./threading.py\", line 964, in start\n",
      "RuntimeError: can't start new thread\n",
      "\n",
      "\n",
      "\n",
      "how_to_communicate_between_threads.example1 FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./example1.py\", line 39, in <module>\n",
      "    t1.start()\n",
      "\n",
      "  File \"./threading.py\", line 964, in start\n",
      "RuntimeError: can't start new thread\n",
      "\n",
      "\n",
      "\n",
      "simple_parallel_programming.findrobots FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./findrobots.py\", line 3, in <module>\n",
      "    import gzip\n",
      "    \n",
      "  File \"./gzip.py\", line 9, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "\n",
      "simple_parallel_programming.findrobots_par FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"./findrobots_par.py\", line 3, in <module>\n",
      "    import gzip\n",
      "    \n",
      "  File \"./gzip.py\", line 9, in <module>\n",
      "ImportError: dynamic libraries are not implemented in wasi\n",
      "\n",
      "\n",
      "\n",
      "how_to_create_a_thread_pool.example2 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "how_to_create_a_thread_pool.example1 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "how_to_create_a_thread_pool.example3 FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/12/how_to_create_a_thread_pool/example3.py\", line 16, in <module>\n",
      "    y = b.result()\n",
      "        ^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/concurrent/futures/_base.py\", line 456, in result\n",
      "    return self.__get_result()\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/concurrent/futures/_base.py\", line 401, in __get_result\n",
      "    raise self._exception\n",
      "  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n",
      "    result = self.fn(*self.args, **self.kwargs)\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/12/how_to_create_a_thread_pool/example3.py\", line 5, in fetch_url\n",
      "    u = urllib.request.urlopen(url)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 216, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 525, in open\n",
      "    response = meth(req, response)\n",
      "               ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 634, in http_response\n",
      "    response = self.parent.error(\n",
      "               ^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 563, in error\n",
      "    return self._call_chain(*args)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 496, in _call_chain\n",
      "    result = func(*args)\n",
      "             ^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/urllib/request.py\", line 643, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 504: Gateway Timeout\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_12 = PYTHON_COOKBOOK.joinpath(\"12\")\n",
    "chapter_12_result = execute_test(chapter_12, get_ignore_list(\"12\"))\n",
    "summarize_result(chapter_12_result)\n",
    "stash_result(chapter_12_result, Path(\"chapter_12_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chatper 13. Utility Scripting And System Administration\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 11/11 [02:08<00:00, 11.66s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 4, <CaseErrorCode.OK: 0>: 4, <CaseErrorCode.BYPASS: 5>: 3, <CaseErrorCode.PY_EXECUTION_TIMEOUT: 7>: 1, <CaseErrorCode.DIFFERENT_RESULT: 4>: 1})\n",
      "\n",
      "parsing_command_line_options.search FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: search.py [-h] -p pattern [-v] [-o OUTFILE] [--speed {fast,slow}]\n",
      "                 [filename ...]\n",
      "search.py: error: the following arguments are required: -p/--pat\n",
      "\n",
      "\n",
      "prompting_for_a_password_at_runtime.example FAILED:\n",
      "PY_EXECUTION_TIMEOUT\n",
      "b'/usr/local/lib/python3.11/getpass.py:91: GetPassWarning: Can not control echo on the terminal.\\n  passwd = fallback_getpass(prompt, stream)\\nWarning: Password input may be echoed.\\nPassword: '\n",
      "\n",
      "generating_a_range_of_ip_addresses_from_a_cidr_address.example FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "putting_limits_on_memory_and_cpu_usage.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Time's up!\n",
      "\n",
      "\n",
      "finding_files.modified_within FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Usage: /workspaces/wamr-with-py/cookbook/src/13/finding_files/modified_within.py dir seconds\n",
      "\n",
      "\n",
      "making_a_stopwatch.stopwatch FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "0.02248743997188285\n",
      "0.044882978952955455\n",
      "-------------------- V.S. --------------------\n",
      "0.11036856996361166\n",
      "0.22061546298209578\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n",
      "executing_an_external_command_and_getting_its_output.example2 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "executing_an_external_command_and_getting_its_output.example1 FAILED:\n",
      "BYPASS\n",
      "\n",
      "\n",
      "getting_the_terminal_size.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/13/getting_the_terminal_size/example.py\", line 2, in <module>\n",
      "    sz = os.get_terminal_size()\n",
      "         ^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: [Errno 25] Inappropriate ioctl for device\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_13 = PYTHON_COOKBOOK.joinpath(\"13\")\n",
    "chapter_13_result = execute_test(chapter_13, get_ignore_list(\"13\"))\n",
    "summarize_result(chapter_13_result)\n",
    "stash_result(chapter_13_result, Path(\"chapter_13_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 14. Testing, Debugging, And Exceptions\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 7/7 [04:04<00:00, 34.98s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 4, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 2, <CaseErrorCode.WASM_EXECUTION_TIMEOUT: 6>: 1, <CaseErrorCode.DIFFERENT_RESULT: 4>: 1})\n",
      "\n",
      "logging_test_output_to_a_file.test FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "make_your_programs_run_faster.example FAILED:\n",
      "WASM_EXECUTION_TIMEOUT\n",
      "None\n",
      "None\n",
      "\n",
      "testing_for_exceptional_conditions_in_unit_tests.test FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "\n",
      "Exception: indirect call type mismatch\n",
      "\n",
      "\n",
      "profiling_and_timing_your_program.timethis FAILED:\n",
      "DIFFERENT_RESULT\n",
      ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n",
      "__main__.countdown : 0.22145235899370164\n",
      "-------------------- V.S. --------------------\n",
      "__main__.countdown : 0.8869439359987155\n",
      "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_14 = PYTHON_COOKBOOK.joinpath(\"14\")\n",
    "chapter_14_result = execute_test(chapter_14, get_ignore_list(\"14\"))\n",
    "summarize_result(chapter_14_result)\n",
    "stash_result(chapter_14_result, Path(\"chapter_14_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Chapter 15. C Extensions\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 16/16 [00:18<00:00,  1.13s/it]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 30, <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 1})\n",
      "\n",
      "working_with_c_strings_of_dubious_encoding.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "working_with_c_strings_of_dubious_encoding.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/working_with_c_strings_of_dubious_encoding/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "passing_null_terminated_strings_to_c_libraries.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "passing_null_terminated_strings_to_c_libraries.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/passing_null_terminated_strings_to_c_libraries/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "wrapping_existing_c_code_with_cython.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/wrapping_existing_c_code_with_cython/setup.py\", line 3, in <module>\n",
      "    from Cython.Distutils import build_ext\n",
      "ModuleNotFoundError: No module named 'Cython'\n",
      "\n",
      "\n",
      "wrapping_existing_c_code_with_cython.setup_alt FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/wrapping_existing_c_code_with_cython/setup_alt.py\", line 3, in <module>\n",
      "    from Cython.Distutils import build_ext\n",
      "ModuleNotFoundError: No module named 'Cython'\n",
      "\n",
      "\n",
      "wrapping_existing_c_code_with_cython.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/wrapping_existing_c_code_with_cython/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "passing_unicode_strings_to_c_libraries.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "passing_unicode_strings_to_c_libraries.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/passing_unicode_strings_to_c_libraries/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "diagnosing_segmentation_faults.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "diagnosing_segmentation_faults.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/diagnosing_segmentation_faults/example.py\", line 2, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "wrapping_c_code_with_swig.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "wrapping_c_code_with_swig.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/wrapping_c_code_with_swig/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "writing_an_extension_function_that_operates_on_arrays.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "writing_an_extension_function_that_operates_on_arrays.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/writing_an_extension_function_that_operates_on_arrays/example.py\", line 2, in <module>\n",
      "    from sample import avg\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "consuming_an_iterable_from_c.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "consuming_an_iterable_from_c.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/consuming_an_iterable_from_c/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "using_cython_to_write_high_performance_array_operations.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/using_cython_to_write_high_performance_array_operations/setup.py\", line 4, in <module>\n",
      "    from Cython.Distutils import build_ext\n",
      "ModuleNotFoundError: No module named 'Cython'\n",
      "\n",
      "\n",
      "using_cython_to_write_high_performance_array_operations.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/using_cython_to_write_high_performance_array_operations/example.py\", line 2, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "defining_and_exporting_c_apis_from_extension_modules.ptsetup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: ptsetup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: ptsetup.py --help [cmd1 cmd2 ...]\n",
      "   or: ptsetup.py --help-commands\n",
      "   or: ptsetup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "defining_and_exporting_c_apis_from_extension_modules.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "defining_and_exporting_c_apis_from_extension_modules.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/defining_and_exporting_c_apis_from_extension_modules/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "accessing_c_code_using_ctypes.sample FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/accessing_c_code_using_ctypes/sample.py\", line 8, in <module>\n",
      "    _mod = ctypes.cdll.LoadLibrary(_path)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/ctypes/__init__.py\", line 454, in LoadLibrary\n",
      "    return self._dlltype(name)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: ../libsample.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "\n",
      "accessing_c_code_using_ctypes.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/accessing_c_code_using_ctypes/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/accessing_c_code_using_ctypes/sample.py\", line 8, in <module>\n",
      "    _mod = ctypes.cdll.LoadLibrary(_path)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/ctypes/__init__.py\", line 454, in LoadLibrary\n",
      "    return self._dlltype(name)\n",
      "           ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/lib/python3.11/ctypes/__init__.py\", line 376, in __init__\n",
      "    self._handle = _dlopen(self._name, mode)\n",
      "                   ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "OSError: ../libsample.so: cannot open shared object file: No such file or directory\n",
      "\n",
      "\n",
      "reading_file_like_objects_from_c.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "reading_file_like_objects_from_c.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/reading_file_like_objects_from_c/example.py\", line 2, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "managing_opaque_pointers_in_c_extension_modules.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "managing_opaque_pointers_in_c_extension_modules.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/managing_opaque_pointers_in_c_extension_modules/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n",
      "turning_a_function_pointer_into_a_callable.example FAILED:\n",
      "WASM_EXECUTION_FAILURE\n",
      "\n",
      "Exception: unreachable\n",
      "\n",
      "\n",
      "writing_a_simple_c_extension_module.setup FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]\n",
      "   or: setup.py --help [cmd1 cmd2 ...]\n",
      "   or: setup.py --help-commands\n",
      "   or: setup.py cmd --help\n",
      "\n",
      "error: no commands supplied\n",
      "\n",
      "\n",
      "writing_a_simple_c_extension_module.example FAILED:\n",
      "PY_EXECUTION_FAILURE\n",
      "Traceback (most recent call last):\n",
      "  File \"/workspaces/wamr-with-py/cookbook/src/15/writing_a_simple_c_extension_module/example.py\", line 1, in <module>\n",
      "    import sample\n",
      "ModuleNotFoundError: No module named 'sample'\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_15 = PYTHON_COOKBOOK.joinpath(\"15\")\n",
    "chapter_15_result = execute_test(chapter_15, get_ignore_list(\"15\"))\n",
    "summarize_result(chapter_15_result)\n",
    "stash_result(chapter_15_result, Path(\"chapter_15_result.pkl\"))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Summary\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 145,\n",
      "         <CaseErrorCode.BYPASS: 5>: 52,\n",
      "         <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 49,\n",
      "         <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 25,\n",
      "         <CaseErrorCode.DIFFERENT_RESULT: 4>: 18,\n",
      "         <CaseErrorCode.PY_EXECUTION_TIMEOUT: 7>: 9,\n",
      "         <CaseErrorCode.WASM_EXECUTION_TIMEOUT: 6>: 2})\n",
      "\n"
     ]
    }
   ],
   "source": [
    "RERUN = True\n",
    "\n",
    "if RERUN :\n",
    "    chapter_x_results = {\n",
    "        **chapter_1_result,\n",
    "        **chapter_2_result,\n",
    "        **chapter_3_result,\n",
    "        **chapter_4_result,\n",
    "        **chapter_5_result,\n",
    "        **chapter_6_result,\n",
    "        **chapter_7_result,\n",
    "        **chapter_8_result,\n",
    "        **chapter_9_result,\n",
    "        **chapter_10_result,\n",
    "        **chapter_11_result,\n",
    "        **chapter_12_result,\n",
    "        **chapter_13_result,\n",
    "        **chapter_14_result,\n",
    "        **chapter_15_result,\n",
    "    }\n",
    "else:\n",
    "    # instead of a re-run, we can load the previous results\n",
    "    chapter_x_results = restore_result(Path(\"cookbook_result.pkl\"))\n",
    "\n",
    "x_counters = Counter([x.error_code for x in chapter_x_results.values()])\n",
    "print()\n",
    "pprint(x_counters)\n",
    "print()\n",
    "\n",
    "stash_result(chapter_x_results, Path(\"cookbook_result.pkl\"))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FAILED: 14.21%\n"
     ]
    }
   ],
   "source": [
    "ALL_CASES_NUM = len(chapter_x_results.keys())\n",
    "VALID_CASES_NUM = ALL_CASES_NUM  \\\n",
    "    - x_counters.get(CaseErrorCode.PY_EXECUTION_FAILURE) \\\n",
    "    - x_counters.get(CaseErrorCode.PY_EXECUTION_TIMEOUT) \\\n",
    "    - x_counters.get(CaseErrorCode.BYPASS)\n",
    "\n",
    "FAILED_RATE = (x_counters.get(CaseErrorCode.WASM_EXECUTION_FAILURE) +\n",
    "               x_counters.get(CaseErrorCode.WASM_EXECUTION_TIMEOUT)) / VALID_CASES_NUM / 1.0\n",
    "print(f\"FAILED: {FAILED_RATE:.2%}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Since the requirement, we don't need to support all the features of python. We willn't count such chapters:\n",
    "- Chapter 11. Network And Web Programming\n",
    "- Chapter 12. Concurrency\n",
    "- Chapter 13. Utility Scripting And System Administration\n",
    "- Chapter 15. C Extensions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Counter({<CaseErrorCode.OK: 0>: 132,\n",
      "         <CaseErrorCode.DIFFERENT_RESULT: 4>: 17,\n",
      "         <CaseErrorCode.WASM_EXECUTION_FAILURE: 2>: 10,\n",
      "         <CaseErrorCode.PY_EXECUTION_FAILURE: 3>: 10,\n",
      "         <CaseErrorCode.BYPASS: 5>: 7,\n",
      "         <CaseErrorCode.WASM_EXECUTION_TIMEOUT: 6>: 2})\n",
      "\n"
     ]
    }
   ],
   "source": [
    "chapter_xxx_results = {\n",
    "    **chapter_1_result,\n",
    "    **chapter_2_result,\n",
    "    **chapter_3_result,\n",
    "    **chapter_4_result,\n",
    "    **chapter_5_result,\n",
    "    **chapter_6_result,\n",
    "    **chapter_7_result,\n",
    "    **chapter_8_result,\n",
    "    **chapter_9_result,\n",
    "    **chapter_10_result,\n",
    "    **chapter_14_result,\n",
    "}\n",
    "\n",
    "\n",
    "x_counters = Counter([x.error_code for x in chapter_xxx_results.values()])\n",
    "print()\n",
    "pprint(x_counters)\n",
    "print()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "FAILED: 7.45%\n"
     ]
    }
   ],
   "source": [
    "ALL_CASES_NUM = len(chapter_xxx_results.keys())\n",
    "VALID_CASES_NUM = ALL_CASES_NUM  \\\n",
    "    - x_counters.get(CaseErrorCode.PY_EXECUTION_FAILURE, 0) \\\n",
    "    - x_counters.get(CaseErrorCode.PY_EXECUTION_TIMEOUT, 0) \\\n",
    "    - x_counters.get(CaseErrorCode.BYPASS, 0)\n",
    "\n",
    "FAILED_RATE = (x_counters.get(CaseErrorCode.WASM_EXECUTION_FAILURE) +\n",
    "               x_counters.get(CaseErrorCode.WASM_EXECUTION_TIMEOUT)) / VALID_CASES_NUM / 1.0\n",
    "print(f\"FAILED: {FAILED_RATE:.2%}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
